atomist/rug

src/main/scala/com/atomist/project/edit/Impact.scala
src/main/scala/com/atomist/rug/kind/dynamic/ViewFinder.scala
src/main/scala/com/atomist/rug/kind/elm/ElmParserCombinator.scala
src/main/scala/com/atomist/rug/runtime/RugOperationSupport.scala
src/test/scala/com/atomist/rug/kind/elm/ElmAddDependencyTest.scala

This replaces a particular exception with a FailedModificationAttempt
and fixes the Elm Parser problem that triggered this confusion
Suggestions on a better place to put this error parsing are welcome. Perhaps it should more generally return FailedModificationAttempt instead of throwing?

On parse error, print bad input

---

src/main/scala/com/atomist/rug/kind/core/ProjectMutableView.scala
src/test/scala/com/atomist/rug/runtime/js/TypeScriptRugEditorTest.scala
src/test/scala/com/atomist/rug/runtime/rugdsl/RugEditorTest.scala

the addFile operation on a project was registering a change even when no change resulted (the same file already existed).
This adds two tests (typescript and rug) and then fixes the bug.

When a file write has no effect, show NoModification

---

src/main/scala/com/atomist/param/ParameterValidationPatterns.scala
src/main/scala/com/atomist/rug/BadRugException.scala
src/main/scala/com/atomist/rug/parser/DefaultIdentifierResolver.scala
src/main/scala/com/atomist/rug/parser/ParserCombinatorRugParser.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperation.scala
src/test/resources/elm-start-static-page/.atomist/editors/NewStaticPage.rug
src/test/scala/com/atomist/param/ParameterTest.scala
src/test/scala/com/atomist/rug/AbstractRuntimeTest.scala
src/test/scala/com/atomist/rug/ConditionsTest.scala
src/test/scala/com/atomist/rug/InterpreterRuntimeTest.scala
src/test/scala/com/atomist/rug/K8Test.scala
src/test/scala/com/atomist/rug/UsesTest.scala
src/test/scala/com/atomist/rug/kind/docker/DockerTypeTestRunnerTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmCaseManipulationTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmExtractModuleTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmTextInputTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmTypeUsageTest.scala
src/test/scala/com/atomist/rug/kind/exec/EditorandReviewerExecutionTest.scala
src/test/scala/com/atomist/rug/kind/js/PackageJsonTest.scala
src/test/scala/com/atomist/rug/kind/python3/PythonTypeUsageTest.scala
src/test/scala/com/atomist/rug/parser/CommonRugParserTest.scala
src/test/scala/com/atomist/rug/parser/RugEditorParserTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperationTest.scala
src/test/scala/com/atomist/rug/runtime/js/TypeScriptRugEditorTest.scala
src/test/scala/com/atomist/rug/runtime/lang/js/NashornConstructorTest.scala
src/test/scala/com/atomist/rug/test/TestRunnerTest.scala
src/test/scala/com/atomist/util/lang/TypeScriptArrayTest.scala

This will break editors at parse time that are not explicitly using ^ and $ to anchor their expressions. 
See #31 for more details.

Enforce anchors and fix all the tests #31

---

src/main/scala/com/atomist/rug/kind/dynamic/ViewFinder.scala
src/main/scala/com/atomist/rug/parser/CommonRugProductionsParser.scala
src/main/scala/com/atomist/rug/parser/CommonRugTokens.scala
src/main/scala/com/atomist/rug/parser/RugParser.scala
src/test/scala/com/atomist/rug/kind/elm/PredicateTest.scala

with @gotcha
Rug predicates have 'and' and 'or.' They should totally have 'not' !
now we can say when not fileContains "src/Main.elm" "Html.beginnerProgram"
which lets us make UpgradeToBeginnerProgram idempotent.

Implement 'not' in predicates

---

src/main/scala/com/atomist/rug/test/RugTestParser.scala
src/main/scala/com/atomist/rug/test/RugTestTokens.scala
src/main/scala/com/atomist/rug/test/TestLoader.scala
src/test/scala/com/atomist/rug/kind/docker/DockerTypeTestRunnerTest.scala
src/test/scala/com/atomist/rug/test/TestRunnerTest.scala
src/test/scala/com/atomist/rug/test/TestScriptParserRugTest.scala

A few class renames, and a single-impl trait rolled in.
r? @johnsonr

Rename RugTestParser so I can find it

---

src/main/scala/com/atomist/util/scalaparsing/CommonTypesParser.scala
src/test/scala/com/atomist/rug/InterpreterRuntimeTest.scala
src/test/scala/com/atomist/rug/parser/CommonRugParserTest.scala
src/test/scala/com/atomist/rug/runtime/rugdsl/RugEditorTest.scala

Regular expressions provided in double-quoted strings were failing to
match because values like `"\\s*"` were being passed to the regex parser
as `\\s*` instead of `\s*`.  This commit makes Rug double-quoted strings
behave like Java double-quoted strings.
Other tests were added as part of trying to track down this issue.

Unescape backslashes in parsed double-quoted string

---

src/main/scala/com/atomist/tree/content/text/microgrammar/MatcherMicrogrammar.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/dsl/MatcherDefinitionParser.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/matchers/Break.scala
src/main/scala/com/atomist/tree/pathexpression/PathExpressionParser.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/MatcherDefinitionParserTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/MatcherDefinitionUsageTest.scala

A break in a microgrammar says "find this terminator; capture it and everything before." It lets you capture the inside of a block, say, or of an XML element.
You could say "If you find a { then grab everything up to and including the }" or "find a `<tr>` and then skip to after the `</tr>`"
(description written by Jess)

Added Break support to microgrammar support

---

src/main/scala/com/atomist/rug/test/TestRunner.scala

Notify them that we haven't implemented it yet.
It will parse, but they won't run. Failing is better than ignoring for now.

In case someone tries to use invocations in the given

---

src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectEditor.scala

This is a tiny naming thing, deconstructing the tuple earlier.

refactor for clarity

---

src/main/scala/com/atomist/tree/pathexpression/LocationStep.scala
src/main/scala/com/atomist/tree/pathexpression/NodeTest.scala
src/main/scala/com/atomist/tree/pathexpression/PathExpressionParser.scala
src/main/scala/com/atomist/tree/pathexpression/Predicate.scala
src/test/scala/com/atomist/tree/pathexpression/PathExpressionEngineTest.scala
src/test/scala/com/atomist/tree/pathexpression/PathExpressionParserTest.scala

This exposes Predicate instances (except for functions) so that they can be used to generate queries to retrieve data, not just against objects in memory.

Made Predicate hierarchy explicit in PathExpressionParser

---

pom.xml

This phase of the build fails silently when node is not installed locally. Later, it means the tests fail in a way that's hard to explain.
This was surprising because the build is supposed to work without node installed. However, tsc doesn't see target/node/node as the node executable.
Christian and I found this today. We'd probably rather require a local node (and tsc?) install, rather than use the node-and-npm plugin because that one stops offline builds from working.
This PR is fine alone, it just makes the build fail with a better message.  Workaround is "install node."
@kipz what do you think about the larger problem?

Fail fast when typescript compile breaks

---

src/main/scala/com/atomist/tree/pathexpression/LocationStep.scala
src/main/scala/com/atomist/tree/pathexpression/NodeTest.scala
src/main/scala/com/atomist/tree/pathexpression/ObjectType.scala
src/main/scala/com/atomist/tree/pathexpression/PathExpressionEngine.scala
src/main/scala/com/atomist/tree/pathexpression/PathExpressionParser.scala
src/main/scala/com/atomist/tree/pathexpression/Predicate.scala
src/test/scala/com/atomist/tree/pathexpression/PathExpressionEngineTest.scala
src/test/scala/com/atomist/tree/pathexpression/PathExpressionParserTest.scala

Note that this changes various signatures, as it's necessary to pass down everything the `ExpressionEngine` needs to evaluate a nested expression in a `Predicate`.

Added NestedPathExpressionPredicate

---

CHANGELOG.md
pom.xml
src/main/scala/com/atomist/project/archive/AtomistConfig.scala
src/main/scala/com/atomist/project/archive/ProjectOperationArchiveReader.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptContext.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptHandlerFinder.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptOperationFinder.scala
src/test/scala/com/atomist/project/archive/ProjectOperationArchiveReaderTest.scala
src/test/scala/com/atomist/rug/TestUtils.scala
src/test/scala/com/atomist/rug/runtime/HandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/TypeScriptRugEditorTest.scala
src/test/scala/com/atomist/util/lang/JavaScriptArrayTest.scala

-   TypeScript/JavaScript should now "export" instances of Rugs inline with CommonJS standard.
Hopefully not a breaking change as there is limited support for automatically exporting legacy ones.
-   Comments are removed from JS files as they are 'required', and relative imports now work correctly
when 'export' is used from TS or vars are added to the global exports var
https://github.com/atomist/rug/issues/156

Fix TS relative imports by forcing all Rugs var to be exported #156

---

src/test/scala/com/atomist/param/ParameterGenerator.scala
src/test/scala/com/atomist/param/ParameterTest.scala
src/test/scala/com/atomist/param/ParametersToTest.scala

Generex generates strings matching the entire regular expression you
provide to it.  Unlike the Java regular expression parser, anchors (^,$)
are not ignored but treated literally.  Since we require these anchors,
remove them from the regular expression before sending it to generex.
Also move generex stuff under test.

Fix generex regex anchor issue

---

src/main/resources/META-INF/services/com.atomist.rug.spi.Typed
src/main/scala/com/atomist/rug/kind/pom/EveryPomType.scala
src/test/scala/com/atomist/rug/kind/pom/EveryPomUsageTest.scala
src/test/scala/com/atomist/rug/kind/pom/PomMutableViewTest.scala
src/test/scala/com/atomist/rug/kind/pom/PomUsageTest.scala

The current `Pom` type only returns the `pom.xml` file from the root of the project. In a multi-module Maven project, it would be useful to be able to iterate through all of the `pom.xml` files. While this can be done with the existing `Xml` type, that loses some of the Maven-specifics of the `Pom` type.
While a different approach could be to simply modify the existing `Pom` type, I think it is more natural to define this as a separate type named `EveryPom`.

introduce a new type which handles every pom.xml file

---

CHANGELOG.md
src/main/scala/com/atomist/project/generate/EditorInvokingProjectGenerator.scala
src/main/scala/com/atomist/project/generate/ProjectGenerator.scala
src/main/scala/com/atomist/rug/rugdoc/TypeDoc.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectGenerator.scala
src/main/scala/com/atomist/rug/ts/TypeScriptInterfaceGenerator.scala
src/main/typescript/node_modules/@atomist/rug/operations/ProjectGenerator.ts
src/test/scala/com/atomist/project/archive/ProjectOperationArchiveReaderTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmNewStaticPageTest.scala
src/test/scala/com/atomist/rug/rugdoc/TypeDocTest.scala
src/test/scala/com/atomist/rug/rugdoc/TypeScriptInterfaceGen.scala
src/test/scala/com/atomist/rug/rugdoc/TypeScriptInterfaceGeneratorTest.scala
src/test/scala/com/atomist/rug/runtime/js/TypeScriptRugEditorTest.scala

The name of the new project is now passed into the ProjectGenerator from the runtime and is accesssible from `ProjectMutableView` via `project.name()`.
This removes the obscure requirement to declare a `project_name` parameter.
refs #192

Remove implicit project_name parameter

---

CHANGELOG.md
src/main/scala/com/atomist/event/archive/HandlerArchiveReader.scala
src/main/scala/com/atomist/rug/kind/service/SimpleMessageBuilder.scala
src/main/scala/com/atomist/rug/kind/service/message.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptContext.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptEventHandler.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptHandlerFinder.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptOperationFinder.scala
src/main/scala/com/atomist/rug/runtime/js/interop/JavaScriptHandlerContext.scala
src/main/scala/com/atomist/rug/runtime/js/interop/NamedJavaScriptEventHandler.scala
src/main/scala/com/atomist/rug/runtime/rugdsl/RugOperationSupport.scala
src/main/scala/com/atomist/rug/ts/TypeScriptInterfaceGenerator.scala
src/main/scala/com/atomist/tree/content/text/TreeNodeOperations.scala
src/main/scala/com/atomist/tree/pathexpression/PathExpressionEngine.scala
src/main/typescript/node_modules/@atomist/rug/operations/Handlers.ts
src/main/typescript/node_modules/@atomist/rug/tree/PathExpression.ts
src/test/scala/com/atomist/event/archive/HandlerArchiveReaderTest.scala
src/test/scala/com/atomist/project/archive/ProjectOperationArchiveReaderTest.scala
src/test/scala/com/atomist/rug/TestUtils.scala
src/test/scala/com/atomist/rug/runtime/HandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/interop/NamedJavaScriptEventHandlerTest.scala

- Current Rug internal APIs remain unchanged (i.e. should have no impact on runtime or CLI)
- Handler archives must have new-style (as per #105) or old 'on' style, but _not_ both
- this is due to how the global var is not injected for the new style, and old handlers would fail to even parse without it.
- Core.ts generation and compilation is now done on-the-fly during tests so we don't need the maven tasks to have run or be online (we still would need to move npm/tsc installation outside of the pom for Travis build to benefit from this).

Handler JS/TS programming model as per atomist/rug#105

---

src/main/scala/com/atomist/rug/InterpreterRugPipeline.scala
src/main/scala/com/atomist/rug/parser/ParserCombinatorRugParser.scala
src/main/scala/com/atomist/rug/parser/RugParser.scala
src/main/scala/com/atomist/rug/runtime/rugdsl/FunctionInvocationContext.scala
src/main/scala/com/atomist/rug/runtime/rugdsl/RugDrivenExecutor.scala
src/main/scala/com/atomist/rug/runtime/rugdsl/RugDrivenProjectEditor.scala
src/main/scala/com/atomist/rug/runtime/rugdsl/RugDrivenProjectPredicate.scala
src/main/scala/com/atomist/rug/runtime/rugdsl/RugDrivenProjectReviewer.scala
src/main/scala/com/atomist/rug/runtime/rugdsl/RugOperationSupport.scala
src/main/scala/com/atomist/rug/test/RugTestParser.scala
src/main/scala/com/atomist/rug/test/TestRunner.scala
src/main/scala/com/atomist/rug/test/TestScenario.scala
src/test/scala/com/atomist/project/archive/ProjectOperationArchiveReaderTest.scala
src/test/scala/com/atomist/rug/parser/CommonRugParserTest.scala
src/test/scala/com/atomist/rug/runtime/js/TypeScriptRugEditorTest.scala
src/test/scala/com/atomist/rug/test/TestRunnerTest.scala
src/test/scala/com/atomist/rug/test/TestScriptParserRugTest.scala

This adds functionality: 
* `generator NewHappyProject` (deprecating @generator editor NewHappyProject)
* You can now test a generator in a rug test.

Support rug-tests for generators

---

src/main/scala/com/atomist/rug/kind/dynamic/ContainerTreeNodeView.scala
src/main/scala/com/atomist/rug/kind/rug/dsl/EditorMutableView.scala
src/main/scala/com/atomist/rug/spi/TerminalView.scala
src/main/scala/com/atomist/tree/content/text/MutableContainerTreeNode.scala
src/main/scala/com/atomist/tree/content/text/MutableTerminalTreeNode.scala
src/main/scala/com/atomist/tree/content/text/TreeNodeOperations.scala
src/main/scala/com/atomist/tree/content/text/grammar/MatchListener.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/Concat.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/Matcher.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/MatcherMicrogrammar.scala
src/main/scala/com/atomist/tree/pathexpression/AxisSpecifier.scala
src/main/scala/com/atomist/tree/pathexpression/NodeTest.scala
src/main/scala/com/atomist/tree/pathexpression/ObjectType.scala
src/main/scala/com/atomist/tree/pathexpression/Predicate.scala
src/main/scala/com/atomist/tree/treeNode.scala
src/main/scala/com/atomist/tree/utils/TreeNodeFinders.scala
src/main/scala/com/atomist/tree/utils/TreeNodeUtils.scala
src/test/scala/com/atomist/rug/runtime/js/interop/NamedJavaScriptEventHandlerTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/MatcherMicrogrammarTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/MicrogrammarUsageInPathExpressionTest.scala

Pulled methods from ContainerTreeNode up. ContainerTreeNode is now a tag trait, which eliminates the need for matching in many places.

Treenode simplification

---

src/main/scala/com/atomist/rug/kind/core/FileType.scala
src/main/scala/com/atomist/rug/kind/core/LineType.scala
src/main/scala/com/atomist/rug/kind/core/ProjectType.scala
src/main/scala/com/atomist/rug/kind/docker/DockerFileType.scala
src/main/scala/com/atomist/rug/kind/dynamic/DefaultViewFinder.scala
src/main/scala/com/atomist/rug/kind/dynamic/ViewFinder.scala
src/main/scala/com/atomist/rug/kind/elm/ElmModuleType.scala
src/main/scala/com/atomist/rug/kind/java/JavaProjectMutableView.scala
src/main/scala/com/atomist/rug/kind/java/JavaSourceType.scala
src/main/scala/com/atomist/rug/kind/java/JavaTypeType.scala
src/main/scala/com/atomist/rug/kind/java/SpringBootProjectMutableView.scala
src/main/scala/com/atomist/rug/kind/js/PackageJsonType.scala
src/main/scala/com/atomist/rug/kind/json/JsonType.scala
src/main/scala/com/atomist/rug/kind/pom/EveryPomType.scala
src/main/scala/com/atomist/rug/kind/pom/PomType.scala
src/main/scala/com/atomist/rug/kind/properties/PropertiesType.scala
src/main/scala/com/atomist/rug/kind/python3/PythonFileType.scala
src/main/scala/com/atomist/rug/kind/python3/PythonRequirementsTxtType.scala
src/main/scala/com/atomist/rug/kind/rug/archive/RugArchiveProjectType.scala
src/main/scala/com/atomist/rug/kind/rug/dsl/RugType.scala
src/main/scala/com/atomist/rug/kind/service/ServicesType.scala
src/main/scala/com/atomist/rug/kind/xml/XmlType.scala
src/main/scala/com/atomist/rug/kind/yml/YmlType.scala
src/main/scala/com/atomist/rug/runtime/rugdsl/RugDrivenProjectPredicate.scala
src/main/scala/com/atomist/rug/runtime/rugdsl/RugOperationSupport.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/MicrogrammarTypeProvider.scala
src/test/scala/com/atomist/rug/kind/test/ReplacerCljType.scala
src/test/scala/com/atomist/rug/kind/test/ReplacerType.scala

View resolvers now look under `TreeNode` instead of `MutableView`. This is a first step on what might amount to removing the need for `MutableView`s altogether.
Note that there are a couple of classes where there's a hacky cast to get to the `evaluator` property of `MutableView`. This isn't a concern as those classes will go when the Rug -> TypeScript transpiler is ready.

Reduced dependency on MutableView: Instead using TreeNode directly.

---

CHANGELOG.md
src/main/scala/com/atomist/tree/marshal/LinkedJsonTreeDeserializer.scala
src/test/scala/com/atomist/tree/marshal/LinkedJsonTreeDeserializerTest.scala

Previously we were creating a new object to update the link. This means
that subsequent updates to those objects were not being reflected by
objects that referenced them: as they were no longer references. This
introduces a wrapper that allows us to override the link name whilst
still holding a reference to the original object so that updates are
reflected across the tree.

Deserialize linked json to arbitrary depth

---

CHANGELOG.md
src/main/scala/com/atomist/tree/marshal/LinkedJsonTreeDeserializer.scala
src/test/scala/com/atomist/tree/marshal/LinkedJsonTreeDeserializerTest.scala

Previously values were strings like "Some(valueInHere)" as it was calling .toString on the object. This fix returns values correctly.

Fix values in LinkedJsonTreeDeserializer

---

src/main/resources/META-INF/services/com.atomist.rug.spi.Typed
src/main/scala/com/atomist/rug/kind/grammar/AntlrRawFileType.scala
src/main/scala/com/atomist/rug/kind/python3/Python3Parser.scala
src/main/scala/com/atomist/rug/kind/python3/PythonFileType.scala
src/main/scala/com/atomist/rug/kind/python3/PythonRawFileType.scala
src/main/scala/com/atomist/tree/MutableTreeNode.scala
src/main/scala/com/atomist/tree/content/text/TreeNodeOperations.scala
src/main/scala/com/atomist/tree/content/text/grammar/antlr/AbstractInMemAntlrGrammar.scala
src/main/scala/com/atomist/tree/content/text/grammar/antlr/AntlrGrammar.scala
src/main/scala/com/atomist/tree/content/text/grammar/antlr/ModelBuildingListener.scala
src/main/scala/com/atomist/tree/pathexpression/NamedNodeTest.scala
src/main/scala/com/atomist/tree/pathexpression/NodeTest.scala
src/main/scala/com/atomist/tree/pathexpression/ObjectType.scala
src/main/scala/com/atomist/tree/simpleTreeNodes.scala
src/test/resources/com/atomist/rug/kind/python3/Imports.ts
src/test/scala/com/atomist/rug/kind/python3/Python3ParserTest.scala
src/test/scala/com/atomist/rug/kind/python3/PythonRawFileTypeUsageTest.scala
src/test/scala/com/atomist/rug/kind/python3/RawPython3Test.scala

Path expressions are wonderful at filtering out noise. This PR adds an easy way of creating a type from a _raw_ tree from an Antlr grammar. If we use path expressions, AST noise is no longer such an issue.
See `PythonRawFileType` for an example.
It also makes path expressions not blow up descending into unknown types.

Antlr tree

---

src/main/scala/com/atomist/rug/kind/grammar/AntlrRawFileType.scala
src/main/scala/com/atomist/rug/kind/python3/PythonRawFileType.scala
src/main/scala/com/atomist/tree/pathexpression/AxisSpecifier.scala
src/main/scala/com/atomist/tree/pathexpression/NamedNodeTest.scala
src/main/scala/com/atomist/tree/pathexpression/NodeTest.scala
src/main/scala/com/atomist/tree/pathexpression/Predicate.scala
src/test/resources/com/atomist/rug/kind/python3/ChangeImports.ts
src/test/resources/com/atomist/rug/kind/python3/Imports.ts
src/test/resources/com/atomist/rug/kind/python3/ListImports.ts
src/test/scala/com/atomist/rug/kind/python3/PythonRawFileTypeUsageTest.scala
src/test/scala/com/atomist/tree/pathexpression/PathExpressionEngineTest.scala

Makes `NamedNodeTest` work under `//`--previously it broke with a match error.
Makes `value` property work in `PropertyValuePredicate`.
Implementation of `PropertyValuePredicate` is a bit inelegant, but we can refine later.

Path expression fixes for //

---

src/main/resources/META-INF/services/com.atomist.rug.spi.Typed
src/main/resources/grammars/antlr/CSharpLexer.g4
src/main/resources/grammars/antlr/CSharpParser.g4
src/main/scala/com/atomist/rug/kind/csharp/CSharpFileType.scala
src/main/scala/com/atomist/rug/kind/grammar/AntlrRawFileType.scala
src/main/scala/com/atomist/rug/kind/javascript/JavaScriptParser.scala
src/main/scala/com/atomist/rug/kind/json/JsonParser.scala
src/main/scala/com/atomist/rug/kind/python3/Python3Parser.scala
src/main/scala/com/atomist/rug/kind/python3/PythonRawFileType.scala
src/main/scala/com/atomist/tree/content/text/grammar/antlr/AbstractInMemAntlrGrammar.scala
src/main/scala/com/atomist/tree/content/text/grammar/antlr/AntlrGrammar.scala
src/test/scala/com/atomist/rug/kind/csharp/CSharpFileTypeTest.scala
src/test/scala/com/atomist/rug/kind/csharp/CSharpFileUsageTest.scala

- Improves Antlr grammar integration (`AntlrGrammar`) to allow for grammars that are split into multiple files (e.g. lever and parser G4 files)
- Brought in C# grammar from Antlr v4 grammars. Converted lexer to use Java instead of C#. We should eventually contribute this back to https://github.com/antlr/grammars-v4/tree/master/csharp.
- Updated existing (and unused) Antler-based types to work with changed signature in `AntlrGrammar`

Improved Antlr integration. Introduced C# grammar.

---

src/main/scala/com/atomist/tree/content/text/TreeNodeOperations.scala
src/main/scala/com/atomist/tree/content/text/ViewTree.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/MatcherMicrogrammar.scala
src/main/scala/com/atomist/tree/utils/TreeNodeUtils.scala

because i can't println a function. Give a description every time.
This helps with debugging in tests, and it makes the code a bit more documented IMO

All TreeOperations and ViewTrees have descriptions

---

CHANGELOG.md
src/main/scala/com/atomist/rug/parser/CommonRugProductionsParser.scala
src/main/scala/com/atomist/tree/pathexpression/PathExpressionParser.scala
src/main/scala/com/atomist/tree/pathexpression/Predicate.scala
src/test/scala/com/atomist/tree/pathexpression/PathExpressionEngineTest.scala
src/test/scala/com/atomist/tree/pathexpression/PathExpressionParserTest.scala
src/test/scala/com/atomist/tree/pathexpression/PathExpressionsAgainstProjectTest.scala

Path expression location steps can have optional predicates, indicated
by appending the predicate block with a question mark, `[...]?`.
Since most path expressions in predicates will be relative to the
context node, support relative tree expressions.  Only absolute path
expressions are allowed at the top level.  Currently, the tree returned
by the parser does not distinguish between relative and absolute paths,
but that can be added later if needed.
Improve toString method for property predicates.

Add optional predicates and relative path expressions

---

src/main/scala/com/atomist/tree/content/text/AbstractMutableContainerTreeNode.scala
src/main/scala/com/atomist/tree/content/text/PositionedTreeNode.scala

Conceptually, pad transforms a node from a PositionedTreeNode to a MutableTreeNode.
conceptually, PositionedTreeNodes must not be updated
while it's OK to update a Mutable TreeNode.
Padding is the transition, when offsets get translated to padding so that
the file can be rewritten by concatenating the values of the nodes.
Each character in the file then belongs to exactly one node.
In practice, in the current codebase, these nodes are all both PositionedTreeNode
and MutableTreeNode, and pad mutates it into MutableTreeNode.
Changing that will be work, so instead:
Make pad a static method that transforms a PositionTreeNode into a MutableTreeNode.
Then shoehorn that into the existing implementation.
This will make pad testable. It's a crucial, complicated method so this is useful.

Make pad a transformation, for conceptual reasons

---

pom.xml
src/main/scala/com/atomist/tree/content/text/AbstractMutableContainerTreeNode.scala
src/test/scala/com/atomist/tree/content/text/PadPropertyTest.scala

Generators for simple Container and Terminal tree nodes,
along with input that could have produced them.
I've set this up to run only ten times per property.
It is only testing a few things, but it's a foundation for more.
Since I hope to refactor pad significantly some day, this will be useful. The generators will also be useful in other tests.

A generative test for pad

---

src/main/scala/com/atomist/rug/kind/csharp/CSharpFileType.scala
src/main/scala/com/atomist/rug/kind/grammar/AntlrRawFileType.scala
src/main/scala/com/atomist/rug/kind/javascript/JavaScriptParser.scala
src/main/scala/com/atomist/rug/kind/json/JsonParser.scala
src/main/scala/com/atomist/rug/kind/python3/PythonFileType.scala
src/main/scala/com/atomist/tree/content/text/SimpleMutableContainerTreeNode.scala
src/main/scala/com/atomist/tree/content/text/grammar/antlr/AntlrGrammar.scala
src/main/scala/com/atomist/tree/content/text/grammar/antlr/ModelBuildingListener.scala

Adds ability to map Antlr node names and types as per `AntlrGrammar` strategy. Useful to map Antlr production names to user-intelligible values.

Antlr naming

---

CHANGELOG.md
src/main/scala/com/atomist/event/archive/HandlerArchiveReader.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptContext.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptHandlerFinder.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperation.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptOperationFinder.scala
src/main/typescript/node_modules/@atomist/rug/operations/RugOperation.ts
src/test/scala/com/atomist/rug/kind/elm/ElmTypeScriptEditorTest.scala
src/test/scala/com/atomist/rug/runtime/HandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptContextTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperationTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptOperationFinderTest.scala
src/test/scala/com/atomist/rug/ts/TypeScriptBuilder.scala
src/test/scala/com/atomist/util/lang/JavaScriptArrayTest.scala

- add support for decorated parameters
- decorate actually just populates the 'parameters' property
- totally backwards compatible and interchangeable
```typescript
import {Project} from '@atomist/rug/model/Core'
import {ProjectEditor} from '@atomist/rug/operations/ProjectEditor'
import {File} from '@atomist/rug/model/Core'
import {parameter} from '@atomist/rug/operations/RugOperation'
class SimpleEditor implements ProjectEditor {
name: string = "Simple"
description: string = "A nice little editor"
@parameter({pattern: "^.*$$", description: "foo bar"})
content: string = "Test String";
@parameter({pattern: "^\\d+$$", description: "A nice round number"})
amount: number = 10;
@parameter({pattern: "^\\d+$$", description: "A nice round number"})
nope: boolean;
edit(project: Project) { …
```

Decorator TS parameters. New js rug instance per invocation #229

---

src/main/scala/com/atomist/tree/content/text/FormatInfo.scala
src/main/scala/com/atomist/tree/content/text/InputPosition.scala
src/main/scala/com/atomist/tree/content/text/OffsetInputPosition.scala
src/main/scala/com/atomist/tree/content/text/PositionedMutableContainerTreeNode.scala
src/main/scala/com/atomist/tree/content/text/SimpleMutableContainerTreeNode.scala
src/test/scala/com/atomist/tree/content/text/FormatInfoTest.scala
src/test/scala/com/atomist/tree/content/text/PositionedMutableContainerTreeNodeTest.scala

Adds the ability to construct a `FormatInfo` object from a direct child field of a `PositionedMutableContainerTreeNode`. This can be used to:
- Return line and column information for the node for reviewers and diagnostics
- Obtain information about the indentation style of the file (tabs vs space; indent depth)
- Format strings to add to the file **while preserving the existing formatting**.
This functionality should help to edit many types of file preserving structure.
Resolves #238.

Detailed node position and format info can be obtained from PositionedMutableContainerTreeNode

---

CHANGELOG.md
src/main/scala/com/atomist/rug/kind/service/SimpleMessageBuilder.scala
src/main/scala/com/atomist/rug/kind/service/message.scala
src/main/scala/com/atomist/tree/marshal/LinkedJsonTreeDeserializer.scala
src/main/typescript/node_modules/@atomist/rug/operations/Handler.ts
src/test/scala/com/atomist/event/archive/HandlerArchiveReaderTest.scala

Some changes required for the CypherTreeMaterializer.
Firstly we need a way of adding a correlationId to a message that can be defined inside the handler.
Secondly we add a new type of ContainerTreeNode where we can hold the JSON map that originally created the TreeNode structure. This allows us to pass the flat JSON representation back when calling send(). This avoids us having to implement a flat JSON serializer and an additional conversion on send().

Add correlationId to Message, add JsonBackedTreeNode

---

CHANGELOG.md
src/main/scala/com/atomist/rug/kind/yml/YmlMutableView.scala
src/main/scala/com/atomist/rug/kind/yml/YmlType.scala
src/test/scala/com/atomist/rug/kind/yml/YmlMutableViewTest.scala

Previously the YAML parser would fail on a YAML file with multiple
documents.  The code will now only parse and operate on the first,
ignoring the rest.

Allow YAML files with multiple documents, but ignore

---

src/main/scala/com/atomist/tree/content/text/microgrammar/Concat.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/DismatchReport.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/Literal.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/Matcher.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/MatcherMicrogrammar.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/Regex.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/Rep.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/matchers/Break.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/primitives.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/MatcherMicrogrammarTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/MatcherOperationsTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/RegexTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/RepTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/WrapTest.scala

Now that any node can be created as Noise, we're free to create them all the time. This simplifies pattern matches a little.

Node is no longer optional in PatternMatch

---

src/main/scala/com/atomist/rug/kind/dynamic/ContainerTreeNodeView.scala
src/main/scala/com/atomist/rug/kind/dynamic/mutableContainerTreeNodeMutableView.scala
src/main/scala/com/atomist/rug/kind/grammar/RawNodeUnderFileMutableView.scala
src/main/scala/com/atomist/rug/spi/ViewSupport.scala
src/main/scala/com/atomist/rug/ts/TypeScriptInterfaceGenerator.scala
src/main/scala/com/atomist/tree/content/text/FormatInfo.scala
src/main/scala/com/atomist/tree/content/text/FormatInfoProvider.scala
src/main/scala/com/atomist/tree/content/text/MutableContainerTreeNode.scala
src/main/scala/com/atomist/tree/content/text/PositionedMutableContainerTreeNode.scala
src/main/scala/com/atomist/util/lang/TypeScriptGenerationHelper.scala
src/main/typescript/node_modules/@atomist/rug/tree/PathExpression.ts
src/test/scala/com/atomist/rug/kind/csharp/CSharpFileTypeTest.scala
src/test/scala/com/atomist/rug/rugdoc/TypeScriptInterfaceGeneratorTest.scala
src/test/scala/com/atomist/tree/content/text/FormatInfoTest.scala
src/test/scala/com/atomist/tree/content/text/PositionedMutableContainerTreeNodeTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/MicrogrammarUsageInPathExpressionTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/TypeScriptMicrogrammarTest.scala

Make it possible to get format info (line, column and indentation info) from any view backed in a positioned tree node structure. Useful for reviewers and adding content respecting existing formatting.

Exposing format info from text views

---

src/main/scala/com/atomist/rug/kind/pom/PomMutableView.scala
src/test/scala/com/atomist/rug/kind/pom/PomMutableViewTest.scala

Currently, there is one way to add scope for existing dependencies. Now,
new operators are added to add scope when dependency is added or
updated.

Add POM's scope element

---

src/main/scala/com/atomist/rug/runtime/js/interop/jsSafeCommittingProxy.scala
src/main/scala/com/atomist/tree/TerminalTreeNode.scala
src/main/scala/com/atomist/tree/content/text/MutableContainerTreeNode.scala
src/main/scala/com/atomist/tree/content/text/grammar/antlr/ModelBuildingListener.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/MatcherMicrogrammar.scala
src/main/scala/com/atomist/tree/treeNode.scala
src/test/resources/com/atomist/rug/kind/csharp/ChangeException.ts
src/test/scala/com/atomist/rug/kind/csharp/CSharpFileTypeUsageTest.scala
src/test/scala/com/atomist/rug/kind/grammar/SimpleMutableContainerTreeNodeTest.scala

Introduces a Dynamic tag for TreeNodes, which is shared between Antlr and the microgrammar support, where an `MicrogrammarNode` annotation was previously used.
Added additional path-expression based test for C# file type to illustrate this.
Deleted `MicrogrammarNode` class and object, as they are no longer needed.
Fixed issue where `FormatInfo` was only obtainable for direct children of a file's root node.

JavaScript property navigation for Antlr-backed nodes

---

CHANGELOG.md
src/main/scala/com/atomist/rug/kind/grammar/RawNodeUnderFileMutableView.scala
src/main/scala/com/atomist/rug/runtime/js/interop/JavaScriptBackedTypeProvider.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsSafeCommittingProxy.scala
src/main/typescript/node_modules/@atomist/rug/tree/PathExpression.ts
src/main/typescript/node_modules/@atomist/rug/tree/TreeHelper.ts
src/test/resources/com/atomist/rug/kind/csharp/AddImport.ts
src/test/resources/com/atomist/rug/kind/csharp/ChangeException.ts
src/test/resources/com/atomist/rug/kind/csharp/ChangeUsing.ts
src/test/resources/com/atomist/rug/kind/csharp/NavigateTree.ts
src/test/resources/com/atomist/rug/kind/python3/ChangeImports.ts
src/test/resources/com/atomist/rug/kind/python3/ListImports.ts
src/test/resources/com/atomist/rug/kind/rug/ReplaceEditorWithGenerator.ts
src/test/resources/com/atomist/rug/runtime/js/interop/MutatingBanana.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleBanana.ts
src/test/resources/com/atomist/rug/runtime/js/interop/TwoLevel.ts
src/test/scala/com/atomist/rug/kind/csharp/CSharpFileTypeUsageTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmTypeScriptEditorTest.scala
src/test/scala/com/atomist/rug/kind/rug/RugFileTypeTest.scala
src/test/scala/com/atomist/rug/kind/rug/RugFileTypeUsageTest.scala
src/test/scala/com/atomist/rug/runtime/js/interop/JavaScriptBackedTypeProviderTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/TypeScriptMicrogrammarTest.scala

Several enhancements for working with tree nodes in TypeScript:
- Pulled text-specific methods in TypeScript `TreeNode` interface into new `TextTreeNode`. No change yet on Scala side.
- Added `TreeHelper.ts` library class to help users navigate tree ancestry. This shows the potential of TypeScript libraries.

TypeScript tree enhancements

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingExecutor.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectEditor.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectGenerator.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperation.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectReviewer.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptOperationFinder.scala
src/main/typescript/node_modules/@atomist/rug/operations/ProjectEditor.ts
src/main/typescript/node_modules/@atomist/rug/operations/ProjectGenerator.ts
src/main/typescript/node_modules/@atomist/rug/operations/ProjectReviewer.ts
src/main/typescript/node_modules/@atomist/rug/operations/RugOperation.ts
src/main/typescript/node_modules/@atomist/rug/tree/TreeHelper.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptOperationFinderTest.scala
src/test/scala/com/atomist/rug/runtime/js/TypeScriptRugEditorTest.scala

Annotations take precedence over equivalent interface fields to avoid any confusion about which are used.
e.g.
```typescript
import {Project} from '@atomist/rug/model/Core'
import {File} from '@atomist/rug/model/Core'
import {editor, parameter, tags} from '@atomist/rug/operations/RugOperation'
@editor("Simple", "My simple editor")
@tags("java", "maven")
class SimpleEditor {
@parameter({description: "Content", displayName: "content", pattern: "$ContentPattern", maxLength: 100, tags: ["foo","bar"]})
content: string
edit(project: Project) {
project.editWith("other", { otherParam: "Anders Hjelsberg is God" })
}
}
export let myeditor = new SimpleEditor()
```

Class level decorator support

---

src/main/scala/com/atomist/rug/kind/scala/ScalaMetaTreeBackedTreeNode.scala
src/main/scala/com/atomist/tree/content/text/SimpleMutableContainerTreeNode.scala
src/test/resources/com/atomist/rug/kind/scala/UpgradeScalaTestAssertions.ts
src/test/scala/com/atomist/rug/kind/scala/ScalaFileTypeTest.scala
src/test/scala/com/atomist/rug/kind/scala/ScalaFileTypeUsageTest.scala
src/test/scala/com/atomist/rug/kind/scala/ScalaMetaBackedTreeNodeTest.scala

Makes `makeMutable` TreeNode utility operation preserve tags.
Also improves pending test for ScalaFileType

Lower cases ScalaMetaTreeNode productions. Allow JS calls on ScalaMetaTreeNode-backed objects

---

src/test/resources/elm-start-static-page/.atomist/editors/NewStaticPage.rug

Stop this warning,
Generator 'NewStaticPage' uses deprecated @generator annotation.
Please remove the @generator annotation and change the 'editor' keyword to 'generator'.

Update from deprecated @generator annotation in test Rug

---

src/test/scala/com/atomist/rug/kind/elm/ElmCaseManipulationTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmExtractModuleTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmNewStaticPageTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmTextInputTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmTypeScriptEditorTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmTypeUsageTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmUpgradeProgramTest.scala
src/test/scala/com/atomist/rug/kind/elm/PredicateTest.scala

- Import `OptionValues._` to allow `.value` on an Option instead of `.get` for
an improved error message when `None`
- Make some methods private - apparently this reduces compile times
- Swap `<string>.contains(<x>) should be (true)` for `<string> should include(<x>)`
- Less code
- Includes string in assertion error avoiding need to add `println` or `withClue`
later
- Collapse multiple include assertions on same string into one` should(..)`
- Add pending in cases where an assertion appears to be missing
- Removed some unused code, commented others.

Use additional ScalaTest features in kind.elm

---

src/main/scala/com/atomist/rug/kind/scala/ScalaMetaTreeBackedTreeNode.scala
src/main/scala/com/atomist/rug/kind/service/ServicesMutableView.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptEventHandler.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingExecutor.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperation.scala
src/main/scala/com/atomist/rug/runtime/js/interop/NamedJavaScriptEventHandler.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsPathExpressionEngine.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsSafeCommittingProxy.scala
src/main/scala/com/atomist/tree/treeNode.scala
src/main/scala/com/atomist/util/lang/TypeScriptGenerationHelper.scala
src/test/resources/com/atomist/rug/kind/scala/UpgradeScalaTestAssertions.ts
src/test/scala/com/atomist/rug/kind/scala/ScalaFileTypeUsageTest.scala
src/test/scala/com/atomist/rug/runtime/js/interop/jsSafeCommittingProxyTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/TypeScriptMicrogrammarTest.scala

`jsSafeCommittingProxy` now proxies objects returned by TypeScript navigation.
Added `children` convenience method on `TreeNode` for JavaScript callers, who can't cope with Scala collections.
Made further `ScalaTypeUsageTest` scenario work.
Also fixes #283

Better js safe committing proxy

---

src/main/scala/com/atomist/rug/kind/rug/dsl/EditorMutableView.scala
src/main/scala/com/atomist/rug/spi/Typed.scala
src/main/scala/com/atomist/util/lang/javaHelpers.scala

[stripSuffix](http://www.scala-lang.org/api/2.11.8/index.html#scala.collection.immutable.StringOps@stripSuffix(suffix:String):String)
```
scala> val a = "asdf.com" :: "asfdf.co" :: "asdf" :: "com.asdf" :: Nil
a: List[String] = List(asdf.com, asfdf.co, asdf, com.asdf)
scala> a map (x => (x, x.endsWith(".com"), x.stripSuffix(".com")))
res7: List[(String, Boolean, String)] = List(
(asdf.com,true,asdf),
(asfdf.co,false,asfdf.co),
(asdf,false,asdf),
(com.asdf,false,com.asdf)
)
```
Next action would be to remove these methods.

Prefer StringOps.stripSuffix to local implementations

---

src/main/scala/com/atomist/rug/runtime/js/JavaScriptEventHandler.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsContextMatch.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsPathExpressionEngine.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsSafeCommittingProxy.scala
src/main/scala/com/atomist/tree/marshal/LinkedJsonTreeDeserializer.scala
src/main/scala/com/atomist/tree/treeNode.scala
src/test/scala/com/atomist/tree/marshal/LinkedJsonTreeDeserializerTest.scala

* `jsSafeCommittingProxy` is itself a `TreeNode` now that delegates earch call to `TreeNode` methods to the proxied/wrapped node
* Properly handle `nodeTags` in `LinkableContainerTreeNode`; add `TreeNode.Dyanamic` to `nodeTags` so that` jsSafeCommittingProxy` allows to dispatch through to childNodes
* `FunctionProxyToNodeNavigationMethods` now exposes `value()` for `TerminalTreeNode`s instead of returning the node

Changes to make neo-tree-materializer work

---

.atomist.yml
.atomist/editors/AddTypeScriptTest.rug
.atomist/manifest.yml
.atomist/templates/AddTypeScriptTestTemplate.vm
.atomist/tests/AddTypeScriptTest.rt
src/test/resources/com/atomist/rug/ts/SampleTypeScriptTest.ts
src/test/scala/com/atomist/rug/ts/SampleTypeScriptTest.scala

I found myself asking yet again, "How can I add a test for this, that uses it in TypeScript?" and I didn't want to add yet another hard-coded test to TypeScriptMicrogrammarTest. I wanted a TypeScript file in resources, and a Scala test to use it. One that is as clear as I can make it about how this works.
Now we can add tests individually for functionalities, and someday this will be useful in language extensions repositories. For now, this editor is only useful in Rug, so it makes sense for it to live here.

Add typescript test, the Editor

---

src/main/scala/com/atomist/param/Parameter.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperation.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/DismatchReport.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/Matcher.scala
src/test/scala/com/atomist/event/archive/HandlerArchiveReaderTest.scala
src/test/scala/com/atomist/project/archive/ProjectOperationArchiveReaderTest.scala
src/test/scala/com/atomist/rug/kind/elm/ElmUpgradeProgramTest.scala
src/test/scala/com/atomist/tree/content/text/PadPropertyTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/RepTest.scala

- Replace x.size > 0 with x.nonEmpty
- Prevent Scaladoc unbalanced tag warning by using code formatting ``
- Avoid PartialFunction when anonymous function sufficient
- Extend reliance on parameter default instead of supplying ")"
- Remove superfluous braces in imports
- Use val when var was set to mutable type
- Remove superfluous headOption (which I added earlier)
- Use x.indices instead of Range(0, x.length)
- Drop new when creating a case class instance

Apply Intellij code analysis fixes

---

CHANGELOG.md
src/main/scala/com/atomist/rug/BadRugException.scala
src/main/scala/com/atomist/rug/test/RugTestParser.scala
src/test/scala/com/atomist/rug/test/TestScriptParserRugTest.scala

This should address #71 when the scenario name is not set.
By raising that specific error, the user gets a message that
the name is invalid (since an empty name is considered as such).
This was much trickier than expected because scala Combinators regex
used before wasn't stopping at the end of the scenario line but
would swallow everythong down to the next production. David and I
figured we'd need to be a little more explicit about the actual
parsing rule.

Raise an InvalidRugTestScenarioName when scenario name is empty

---

src/main/scala/com/atomist/util/lang/JavaScriptArray.scala

Whereas Scala `Int` and Java `Integer` have different names, Scala `Double`
and Java `Double` have the same name so this,
d: Double => ...
is a typed pattern requiring `scala.Double` a subclass of `AnyVal` which `ret` as `AnyRef` cannot satisfy.
Credit to IntelliJ,

Fix "pattern type is incompatible with expected type"

---

pom.xml

This makes it easy to find the failed tests when building on console.
Example,
I feel this would be a benefit to future contributors.

Configure ScalaTest to dump short account of failed tests at end of build

---

src/main/scala/com/atomist/rug/runtime/rugdsl/DefaultViewFinder.scala
src/main/scala/com/atomist/rug/runtime/rugdsl/RugOperationSupport.scala

sample:
```
<unknown>: Cannot find 'elmModule' under OverwriteableTextTreeNode[length=129][name=elmModule]. It does have these children: OverwriteableText,-dynamic,import,module declaration,function,PositionedSyntaxNode
```

Improve a Rug DSL error message when a language extension isn't found

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/JavaScriptEventHandler.scala
src/test/scala/com/atomist/rug/runtime/js/interop/NamedJavaScriptEventHandlerTest.scala

Means we can start with /Pipeline() not just /Pipeline which means we
can match PE on nodeTag not just nodeName

Support path expression starting with NodesWithTag

---

src/main/scala/com/atomist/rug/runtime/execution/LocalPlanExecutor.scala
src/main/scala/com/atomist/rug/runtime/execution/PlanExecutor.scala
src/main/scala/com/atomist/rug/spi/Handlers.scala
src/main/scala/com/atomist/rug/spi/JavaHandlers.scala
src/test/scala/com/atomist/rug/runtime/execution/LocalPlanExecutorTest.scala

Nothing changes here with the way that the plan executes, just what is returned.
Previously there was a poor attempt at keeping up with plan execution errors and instruction responses by storing them in Maps. There were several problems with this approach. The keys were not guaranteed to be unique which would allow data to be overwritten. Also, instruction executions can be done in parallel and might step on each other when updating the Maps.
A better way is to just keep a growing Seq of interesting events during the plan, and combine the events from the different futures.
Additionally, a PlanResult now keeps references to nested plan executions as Futures.

Better handling of Plan execution results.

---

src/main/scala/com/atomist/util/scalaparsing/CommonTypesParser.scala
src/test/scala/com/atomist/rug/parser/CommonRugParserTest.scala

The previous regex was provoking a stackoverflow on a JVM 32 bits.
The regex proposed by @ddgenome does do the trick without
breaking existing Rugs as far the tests tell us.
Closes #337.

Parse Rug C-style comments properly

---

.atomist.yml
src/main/scala/com/atomist/rug/spi/HandlerUtil.scala
src/main/scala/com/atomist/rug/tree/utils/TreeNodePrinter.scala
src/test/scala/com/atomist/rug/runtime/plans/LocalPlanRunnerTest.scala
src/test/scala/com/atomist/rug/tree/utils/TreeNodePrinterTest.scala

Add a utility for printing Plans and PlanEventLogs
```
Plan
├── Edit edit1 None List()
├─┬ Edit edit2 None List()
| ├─┬ onSuccess
| | └── Message: MessageText(pass), like List()
| └─┬ onFailure
|   └── Message: MessageText(fail), like List()
├─┬ Edit edit3 None List()
| └─┬ onSuccess
|   └── Respond respond1 None List()
├─┬ Edit edit4 None List()
| └─┬ onSuccess
|   └─┬ Plan
|     └── Message: MessageText(nested plan), like List()
└── Message: MessageText(message1), like List(Presentable(Generate(Detail(generate1,None,List())),Some(label1)))
```
Then use this for comparison in the test; string diffs become tree diffs when the assertion fails.

Print event logs

---

src/main/scala/com/atomist/rug/kind/ServiceLoaderTypeRegistry.scala
src/main/scala/com/atomist/rug/runtime/plans/ServiceLoaderRugFunctionRegistry.scala
src/main/scala/com/atomist/util/ServiceLoaderBackedExtensionProvider.scala

In a shared classloader environment the previous approach using lazy, only loaded Types and RugFunctions for the first archvie/classpath. Now the cache is keyed by ClassLoader with weak reference so the ClassLoader can get collected if possible.

Cache serviceloader results keyed by ClassLoader

---

src/main/java/com/atomist/rug/runtime/plans/InstructionRunner.java
src/main/java/com/atomist/rug/runtime/plans/MessageDeliverer.java
src/main/scala/com/atomist/rug/runtime/InstructionResponse.scala
src/main/scala/com/atomist/rug/runtime/ResponseHandler.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandler.scala
src/main/scala/com/atomist/rug/runtime/js/JsonSerializer.scala
src/main/scala/com/atomist/rug/runtime/js/PlanBuilder.scala
src/main/scala/com/atomist/rug/runtime/plans/LocalInstructionRunner.scala
src/main/scala/com/atomist/rug/runtime/plans/LocalPlanRunner.scala
src/main/scala/com/atomist/rug/runtime/plans/PlanResultInterpreter.scala
src/main/scala/com/atomist/rug/runtime/plans/PlanRunner.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/plans/ExampleRugFunction.scala
src/test/scala/com/atomist/rug/runtime/plans/LocalPlanRunnerTest.scala
src/test/scala/com/atomist/rug/runtime/plans/PlanResultInterpreterTest.scala
src/test/scala/com/atomist/rug/runtime/plans/RugFunctionRegistryTest.scala

- Also serialize response from Rug Functions to JSON if not already
strings (we can loosen this later if we like, but this restriction keeps them serializable for now).
- Remove InstructionResponse - now Response turtles all the way down
No CHANGELOG as just changing/fixing up an unreleased feature.

JSON serialize complex params in Plans

---

src/main/scala/com/atomist/rug/BadRugException.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandler.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptUtils.scala
src/main/scala/com/atomist/rug/runtime/js/JsonSerializer.scala
src/main/scala/com/atomist/rug/runtime/plans/JsonResponseCoercer.scala
src/main/scala/com/atomist/rug/runtime/plans/LocalInstructionRunner.scala
src/main/scala/com/atomist/rug/runtime/plans/ResponseCoercer.scala
src/main/scala/com/atomist/rug/spi/AnnotatedRugFunction.scala
src/main/scala/com/atomist/rug/spi/RugFunction.scala
src/main/typescript/node_modules/@atomist/rug/operations/Decorators.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/plans/ExampleAnnotatedRugFunction.scala
src/test/scala/com/atomist/rug/runtime/plans/ExampleRugFunction.scala
src/test/scala/com/atomist/rug/runtime/plans/RugFunctionRegistryTest.scala

- Restrict RugFunction response to contain Strings or Array[Byte]
- This is so that we can reserve the option to run this workload elsewhere
- Add support (via decorators) for ResponseHandler to coerce response
- Currently on @ParseJson supported
Example taken from a test:
```typescript
class JsonResponder implements HandleResponse<any>{
handle(@ParseJson response: Response<any>) : Plan {
let results = response.body() as any;
if(results.yaml != "is more annoying than json") { throw new Error("Rats: " + results.json)}
results.reasons.map(r => r.main.length)
return new Plan();
}
}
```

Add response coercion support

---

src/main/scala/com/atomist/rug/test/gherkin/AbstractExecutableFeature.scala
src/main/scala/com/atomist/rug/test/gherkin/GherkinRunner.scala
src/main/scala/com/atomist/rug/test/gherkin/ProjectManipulationFeature.scala
src/test/scala/com/atomist/rug/test/gherkin/GherkinRunnerTest.scala

This is needed to remove the printlns from GherkinRunner and co.
I'm going to rebase Rod's `test-handlers` branch once this is merged into `master`.

Add most basic test execution listener

---

.atomist.yml
.atomist/manifest.yml
.atomist/package.json
src/main/scala/com/atomist/tree/content/text/microgrammar/MatcherMicrogrammarConstruction.scala
src/main/typescript/node_modules/@atomist/rug/tree/Microgrammars.ts
src/main/typescript/node_modules/@atomist/rug/tree/PathExpression.ts
src/test/resources/com/atomist/tree/content/text/microgrammar/MatcherMicrogrammarConstructionTypeScriptTest.ts
src/test/scala/com/atomist/tree/content/text/microgrammar/MatcherMicrogrammarConstructionTypeScriptTest.scala

The next step in Microgrammars is being able to specify all the different matchers, from TypeScript.
Currently, the only way to make a microgrammar is to specify the matcher as a string, which is then parsed. The parser is only implemented for a few matchers.
I don't intend to expand the parser - the target instead is to provide constructors in TypeScript for the other types.
I implemented one, for Or. Please comment on this implementation before I add a bunch of others.
Check the test first, in MatcherMicrogrammarConstructorTypeScriptTest.ts
This calls on a new file in @atomist/rug, Microgrammars.ts -- but the type inside is a MicroMatcher (naming advice welcome). A Microgrammar is a type that can be added to a pxe; a Matcher is not (but I thought "Matcher" was too general). A …

A first microgrammar constructor

---

.atomist.yml
src/main/scala/com/atomist/rug/runtime/js/interop/jsSafeCommittingProxy.scala
src/main/typescript/node_modules/@atomist/rug/ast/scala/Types.ts
src/test/resources/com/atomist/rug/kind/scala/UpgradeScalaTestAssertions.ts
src/test/resources/com/atomist/rug/ts/SampleTypeScriptTest.ts
src/test/resources/com/atomist/tree/content/text/microgrammar/MultipleUseOfSubmatcherTypeScriptTest.ts
src/test/scala/com/atomist/tree/content/text/microgrammar/MultipleUseOfSubmatcherTypeScriptTest.scala

This is a change in how we wrap the results of childNodes.
We were throwing them away if we got more than one. Now we return our JavaScriptArray wrapper.

bug fix: Multiple uses of submatcher returned only the first one

---

CHANGELOG.md
src/main/scala/com/atomist/rug/test/gherkin/DefaultExecutableFeatureFactory.scala
src/test/scala/com/atomist/rug/test/gherkin/GherkinReaderTest.scala
src/test/scala/com/atomist/rug/test/gherkin/handler/command/CommandHandlerTestTargets.scala
src/test/scala/com/atomist/rug/test/gherkin/handler/command/GherkinRunnerCommandHandlerTest.scala
src/test/scala/com/atomist/rug/test/gherkin/handler/event/EventHandlerTestTargets.scala
src/test/scala/com/atomist/rug/test/gherkin/handler/event/GherkinRunnerEventHandlerTest.scala
src/test/scala/com/atomist/rug/test/gherkin/project/GherkinRunnerAgainstProjectTest.scala
src/test/scala/com/atomist/rug/test/gherkin/project/ProjectTestTargets.scala

While the singular is more common, it would be best to do this
consistently, i.e., change all .atomist subdirectories to be singular,
and allowing for backward compatibility for a release or two.

Move test directory back to tests

---

CHANGELOG.md
src/main/scala/com/atomist/rug/test/gherkin/project/ProjectScenarioWorld.scala
src/main/typescript/node_modules/@atomist/rug/test/project/Core.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/command/CommandHandlers.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/command/SingleMessageFeature1Steps.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/command/SingleMessageFeature1StepsWithMatchingPathExpression.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/EventHandlers.ts
src/test/resources/com/atomist/rug/test/gherkin/project/SimpleGenerator.ts
src/test/resources/com/atomist/rug/test/gherkin/project/SimpleGeneratorWithParams.ts
src/test/resources/com/atomist/tree/content/text/microgrammar/MultipleUseOfSubmatcherTypeScriptTest.ts
src/test/scala/com/atomist/rug/test/gherkin/GherkinReaderTest.scala
src/test/scala/com/atomist/rug/test/gherkin/project/GherkinRunnerAgainstProjectTest.scala
src/test/scala/com/atomist/rug/test/gherkin/project/ProjectTestTargets.scala
src/test/scala/com/atomist/rug/ts/TypeGeneratorTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/MicrogrammarPathExpressionTest.scala

Ensure project object has an appropriate name.
Fixes #425 and #436 (in separate commits).
Clean up of TypeScript, Gherkin, and change log.
Make test quieter by removing/commenting out `println`'s and `console.log()`'s.

Project name

---

CHANGELOG.md
src/main/typescript/node_modules/@atomist/rug/gulpfile.js
src/main/typescript/node_modules/@atomist/rug/test/handler/Core.ts
src/main/typescript/node_modules/@atomist/rug/test/project/Core.ts
src/main/typescript/node_modules/@atomist/rug/test/project/WellKnownSteps.ts

Add a well-known step for the DSL ArchiveRoot.
Include the test directory in the generated TypeDoc (is there a reason
operations and tree are not?).
Clean up TypeScript formatting.
Make TypeDoc on ScenarioWorld.modificationsMade clear that the initial
population of the project by a generator does not count as a
modification.
Possible closes #426

Add ArchiveRoot step, TypeDoc test

---

CHANGELOG.md
src/main/typescript/node_modules/@atomist/rug/ast/AstHelper.ts
src/main/typescript/node_modules/@atomist/rug/ast/TextTreeNodeOps.ts
src/main/typescript/node_modules/@atomist/rug/ast/java/Types.ts
src/main/typescript/node_modules/@atomist/rug/tree/TreeHelper.ts
src/test/resources/com/atomist/rug/K8Redeploy.ts
src/test/resources/com/atomist/rug/kind/csharp/NavigateTree.ts
src/test/resources/com/atomist/rug/kind/docker/DockerUpgrade.ts
src/test/resources/com/atomist/rug/kind/docker/DockerUpgrade2.ts
src/test/resources/com/atomist/rug/kind/docker/DockerUpgrade3.ts
src/test/resources/com/atomist/rug/kind/java/ClassAnnotated.ts
src/test/resources/com/atomist/rug/kind/pom/EveryPomEdit.ts
src/test/resources/com/atomist/rug/kind/scala/EqualsToSymbol.ts
src/test/resources/com/atomist/rug/runtime/js/interop/MutatingBanana.ts

This removes the `TreeHelper` class in TypeScript, which was not needed as function export is simpler. It also cleans up some TypeScript in the test suite that was created by the old Rug transpired, and reduces console logging in tests.

TypeScript cleanup

---

src/main/typescript/node_modules/@atomist/rug/test/project/Core.ts
src/test/resources/com/atomist/rug/test/gherkin/project/AlpEditors.ts
src/test/resources/com/atomist/rug/test/gherkin/project/EditorWithParametersSteps.ts
src/test/resources/com/atomist/rug/test/gherkin/project/EditorWithoutParametersSteps.ts

Calling `editWith()` and `generateWith()` in TypeScript without a
second argument resulted in an exception since the underlying method
in Scala did not provide a default value.  Given @alankstwewart
finding issues with method overloading, to fix I just made the second
argument not optional in the TypeScript interface.
When EditorWithParametersSteps got moved to its own file, it lost its
parameter.

Parameters are not optional, fix regression

---

CHANGELOG.md
src/main/scala/com/atomist/rug/test/gherkin/project/ProjectScenarioWorld.scala
src/test/resources/com/atomist/rug/test/gherkin/project/AlpEditors.ts
src/test/resources/com/atomist/rug/test/gherkin/project/EditorWithBadParametersSteps.ts
src/test/scala/com/atomist/rug/test/gherkin/project/GherkinRunnerAgainstProjectTest.scala
src/test/scala/com/atomist/rug/test/gherkin/project/ProjectTestTargets.scala

Pass the InvalidParameterException up through editor calls so they get
recorded and you do not hit `???` and blow up when checking if the
editor checks parameters.
Fixes #444

Fix editor testing with bad parameters

---

src/main/typescript/node_modules/@atomist/rug/operations/ProjectReviewer.ts
src/main/typescript/node_modules/@atomist/rug/operations/RugOperation.ts
src/test/resources/com/atomist/rug/runtime/js/TwoReviewers.ts
src/test/scala/com/atomist/rug/runtime/js/TypeScriptRugReviewerTest.scala

Fixes #147 by adding convenient static `combine` method to `ReviewResult`.

Added ReviewResult.combine method to fix #147

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/PlanBuilder.scala
src/main/typescript/node_modules/@atomist/rug/operations/Handlers.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerReturningEmptyMessage.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala

We often see the following in handlers:
```typescript
let message = new Message("");
```
This PR just allows the following which is a totally valid use case:
```typescript
let message = new Message();
```

Allow construction of Message without a body

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/interop/jsPathExpressionEngine.scala
src/main/typescript/node_modules/@atomist/rug/ast/AstHelper.ts
src/main/typescript/node_modules/@atomist/rug/ast/scala/Types.ts
src/main/typescript/node_modules/@atomist/rug/operations/Handlers.ts
src/main/typescript/node_modules/@atomist/rug/operations/PlanUtils.ts
src/main/typescript/node_modules/@atomist/rug/tree/PathExpression.ts
src/main/typescript/node_modules/@atomist/rug/tree/TransformingPathExpressionEngine.ts
src/test/resources/com/atomist/rug/kind/xml/UpgradeVersion.ts
src/test/scala/com/atomist/rug/kind/xml/XmlFileTypeUsageTest.scala

- Cleanup of `PathExpressionEngine` signatures to use `|` to allow `string` or `PathExpression` to be passed in
- Added `PlanUtils` to allow instructions to be created from instantiated operations for type safety
- Export unexported but public types in `Handlers.ts`
- Added realistic `UpgradeVersion` editor to test suite to strengthen XML tests and flush out required functionality

TypeScript library polishing

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/JavaScriptEventHandler.scala
src/main/scala/com/atomist/rug/runtime/js/SimpleContainerGraphNode.scala
src/main/scala/com/atomist/tree/pathexpression/NodesWithTag.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/interop/NashornBackedGraphNodeTest.scala
src/test/scala/com/atomist/tree/QueryByExampleTest.scala

This stops path expressions such as `/Build()` from blowing up when they don't match.
@jessitron I added the dynamic tag to disambiguate between cases where it's OK to blow up on Nodes that don't exist and where it's impossible for us to know.
Hopefully this means we don't regress on this issue:
https://github.com/atomist/rug/issues/323
That I found (where this behaviour was introduced). The tests added for that case still pass so I think this solves both issues.

Allow empty results on NodesWithTag when dynamic

---

src/main/scala/com/atomist/rug/test/gherkin/AbstractExecutableFeature.scala
src/main/scala/com/atomist/rug/test/gherkin/ScenarioWorld.scala
src/main/scala/com/atomist/rug/test/gherkin/handler/event/EventHandlerScenarioWorld.scala
src/test/resources/com/atomist/rug/test/gherkin/handler/event/FailingFeature1Steps.ts
src/test/scala/com/atomist/rug/test/gherkin/handler/event/GherkinRunnerEventHandlerTest.scala

The test support used the default value for `Option` - `null` rather than `None` and therefore failed with an NPE when trying to retrieve a handler if none was registered. Fixed this bug and also captured the message from a `Throwable` that caused the scenario to abort to display to the user in test results.

Improved test message on failure if scenario aborted

---

src/main/scala/com/atomist/rug/test/gherkin/AbstractExecutableFeature.scala
src/main/typescript/node_modules/@atomist/rug/test/handler/Core.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/FailsDueToError.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/PassingFeature1Steps2d.ts
src/test/scala/com/atomist/rug/test/gherkin/handler/event/GherkinRunnerEventHandlerTest.scala

Allowing a void returning allow users to use assertion frameworks such as chai.

Allow void returns for Then steps

---

src/main/scripts/gh-publish.bash
src/main/typescript/node_modules/@atomist/cortex/gulpfile.js
src/main/typescript/node_modules/@atomist/rug/gulpfile.js

Remove `typedoc` from node modules `rug` and `cortex`.

Move typedoc outside of the node module

---

CHANGELOG.md
src/main/scala/com/atomist/rug/test/gherkin/AbstractExecutableFeature.scala
src/main/typescript/node_modules/@atomist/rug/test/handler/Core.ts
src/main/typescript/node_modules/@atomist/rug/test/handler/WellKnownSteps.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/command/SingleMessageFeature1StepsWithMatchingPathExpression.ts

We now only pass the world once to handler tests, by checking whether the fixture is in fact different. It _is_ different for project tests, but not for handler tests.

Pass the world only once to handler tests

---

src/main/scala/com/atomist/rug/runtime/js/JavaScriptEventHandler.scala
src/main/scala/com/atomist/rug/runtime/js/interop/NashornMapBackedGraphNode.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsContextMatch.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsPathExpressionEngine.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsSafeCommittingProxy.scala
src/main/scala/com/atomist/rug/test/gherkin/handler/AbstractHandlerScenarioWorld.scala
src/main/scala/com/atomist/rug/ts/AbstractTypeScriptGenerator.scala
src/main/scala/com/atomist/rug/ts/TypeScriptInterfaceGenerator.scala
src/main/scala/com/atomist/rug/ts/TypeScriptStubClassGenerator.scala
src/main/scala/com/atomist/tree/TreeNode.scala
src/main/scala/com/atomist/util/lang/TypeScriptGenerationHelper.scala
src/main/scala/com/atomist/util/misc/SerializationFriendlyLazyLogging.scala
src/test/resources/com/atomist/rug/test/gherkin/handler/event/EventHandlersAgainstGenerated.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/PassingFeature1StepsAgainstGeneratedWithArrays.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/PassingFeature2Steps1.ts
src/test/scala/com/atomist/rug/test/gherkin/handler/event/GherkinRunnerEventHandlerTest.scala
src/test/scala/com/atomist/rug/ts/CortexTypeGeneratorTest.scala

- Fixes #486. Makes generated code easier for users to understand. Also polishes generation of TypeDoc.
- Fixes #487: Array types can now be populated in stub classes, and the values retrieved.
- Reduces coupling to `jsSafeCommittingProxy` throughout codebase.

Fixes #486 and #487: Improved TypeScript stub class generation

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandler.scala
src/main/scala/com/atomist/rug/runtime/js/PlanBuilder.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsScalaHidingProxy.scala
src/main/scala/com/atomist/rug/runtime/plans/LocalPlanRunner.scala
src/main/scala/com/atomist/rug/runtime/plans/PlanUtils.scala
src/main/scala/com/atomist/rug/spi/Handlers.scala
src/main/typescript/node_modules/@atomist/rug/operations/Handlers.ts
src/main/typescript/node_modules/@atomist/rug/test/handler/Core.ts
src/test/resources/com/atomist/project/archive/MyHandlers.ts
src/test/resources/com/atomist/rug/runtime/js/KittieFetcher.ts
src/test/resources/com/atomist/rug/runtime/js/KittieFetcherWithMappedParams.ts
src/test/resources/com/atomist/rug/runtime/js/interop/KittieFetcherWithSecrets.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerExecuteInstructionCallingRespondable.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerReturningEmptyMessage.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerReturningMessage.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerWithBadStubUse.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerWithNullDefault.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandWithPresentable.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/command/CommandHandlers.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/EventHandlers.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/EventHandlersAgainstGenerated.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/PassingFeature1Steps2d.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/PlanBuilderTest.scala
src/test/scala/com/atomist/rug/runtime/plans/LocalPlanRunnerTest.scala
src/test/scala/com/atomist/rug/runtime/plans/PlanResultInterpreterTest.scala
src/test/scala/com/atomist/rug/runtime/plans/PlanResultLoggerTest.scala

There are now three distinct message types:
- DirectedMessage: body/address enforced
- LifecycleMessage: node enforced
- ResponseMessage: only body enforced

Move to more specific message types in Plans #501

---

CHANGELOG.md
README.md
pom.xml
src/main/scala/com/atomist/rug/ts/AbstractTypeScriptGenerator.scala
src/main/scala/com/atomist/rug/ts/CortexTypeGenerator.scala
src/main/scala/com/atomist/rug/ts/CortexTypeGeneratorApp.scala
src/main/scala/com/atomist/rug/ts/TypeScriptInterfaceGenerator.scala
src/main/scala/com/atomist/rug/ts/TypeScriptStubClassGenerator.scala
src/test/scala/com/atomist/rug/rugdoc/TypeScriptInterfaceGen.scala
src/test/scala/com/atomist/rug/rugdoc/TypeScriptInterfaceGeneratorTest.scala
src/test/scala/com/atomist/rug/rugdoc/TypeScriptStubClassGeneratorTest.scala
src/test/scala/com/atomist/rug/ts/TypeScriptBuilder.scala

Use Maven properties in POM where possible.
Make the generation of rug TypeScript more similar to the cortex
TypeScript generation, providing the root path on the command line
rather than the combined file.  Move `outputPathParam` instance val to
static object val `OutputPathParam`.
More fully document release process, which has become significantly
more complicated.

Clean and document build and release

---

src/main/scala/com/atomist/rug/runtime/js/PlanBuilder.scala
src/main/scala/com/atomist/rug/spi/Handlers.scala
src/main/typescript/node_modules/@atomist/rug/operations/Handlers.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala

EventHandlers must set this so that the bot can correlate the messages.

Add lifecycleId to LifecycleMessage

---

CHANGELOG.md
README.md
src/main/scala/com/atomist/rug/ts/TypeScriptStubClassGenerator.scala

The Stubs.ts file essentially duplicates the capabilities of the
Types.ts file, less elegantly.  We should promote the use of the
Types.ts file since it imports all the classes and is symmetrical with
the Types.ts for the interfaces.

No longer create cortex combined Stubs.ts

---

src/main/scala/com/atomist/project/archive/RugResolver.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptContext.scala
src/test/resources/com/atomist/rug/test/gherkin/handler/event/PassingFeature1StepsAgainstGenerated3.ts

Backward-compatible in Scala through use of default parameter. Will break Java callers, but necessary.

Adds ability for RugResolver to initialize NashornScriptEngine before use

---

src/main/scala/com/atomist/rug/runtime/js/JavaScriptContext.scala

Instead of putting an JDK internal class into our public API, let's go with `ScriptEngine` instead.

Change to public API

---

src/main/scala/com/atomist/rug/kind/DefaultTypeRegistry.scala
src/main/scala/com/atomist/rug/kind/ServiceLoaderTypeRegistry.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsSafeCommittingProxy.scala
src/main/typescript/node_modules/@atomist/rug/ast/scala/Types.ts
src/main/typescript/node_modules/@atomist/rug/operations/Handlers.ts
src/test/resources/com/atomist/rug/kind/csharp/ChangeException.ts
src/test/resources/com/atomist/rug/kind/csharp/NavigateTree.ts
src/test/resources/com/atomist/rug/kind/scala/EqualsToSymbol.ts
src/test/resources/com/atomist/rug/kind/scala/UpgradeScalaTestAssertions.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/command/CommandHandlers.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/EventHandlers.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/Nodes.ts
src/test/resources/com/atomist/rug/tree/context/text/MicrogrammarTypeScriptSampleEditor.ts
src/test/resources/com/atomist/rug/tree/context/text/MicrogrammarTypeScriptTest.ts
src/test/resources/com/atomist/tree/content/text/OverwritableTextTreeNodeTypeScriptTest.ts
src/test/resources/com/atomist/tree/content/text/microgrammar/MultipleUseOfSubmatcherTypeScriptTest.ts
src/test/scala/com/atomist/rug/rugdoc/TypeScriptStubClassGeneratorTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/interop/jsSafeCommittingProxyTest.scala
src/test/scala/com/atomist/rug/tree/context/text/MicrogrammarTypeScriptTest.scala
src/test/scala/com/atomist/rug/ts/CortexTypeGeneratorTest.scala
src/test/scala/com/atomist/tree/content/text/OverwritableTextTreeNodeTypeScriptTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/TypeScriptMicrogrammarTest.scala
src/test/scala/com/atomist/tree/marshal/LinkedJsonTreeDeserializerTest.scala
src/test/scala/com/atomist/tree/marshal/ProxyAgainstDeserializedNodeTest.scala

Fixes bug where navigation of graph (vs invocation of properties defined on a JVM-backed type) did not support property access. This had not shown up because use of the generated model was tested only via Gherkin support, which does not serialize or deserialize nodes.
The fixed behavior is in `jsSafeCommittingProxy`. Most of the changes relate to updating the test suite.
Added tests to verify correct behavior with deserialized ingester nodes and prevent regression.

Property access now used for node navigation

---

src/main/scala/com/atomist/rug/spi/AnnotatedRugFunction.scala

InvocationTargetException has a null message so unwrap it and throw the cause. This will show up in the cli with -X at least

slightly better exception reporting: InvocationTargetException on rug function

---

CHANGELOG.md
src/main/scala/com/atomist/rug/kind/core/ProjectMutableView.scala
src/main/typescript/node_modules/@atomist/rug/test/project/Core.ts
src/main/typescript/node_modules/@atomist/rug/test/project/WellKnownSteps.ts
src/test/resources/com/atomist/rug/test/gherkin/project/CorruptionTestSteps.ts
src/test/scala/com/atomist/rug/kind/core/ProjectMutableViewTest.scala
src/test/scala/com/atomist/rug/test/gherkin/project/ProjectTestTargets.scala

- Project test steps can now return `void` to be consistent with handlers
- Additional convenience methods in `wellKnownSteps` to look for file content, using regular expressions
- New `copyEditorBackingProject ` method on `ProjectMutableView` to copy non-Atomist content conveniently.

Various improvements for project testing

---

CHANGELOG.md
src/main/typescript/node_modules/@atomist/rug/operations/Handlers.ts
src/main/typescript/node_modules/@atomist/rug/test/handler/Core.ts
src/test/resources/com/atomist/project/archive/MyHandlers.ts
src/test/resources/com/atomist/rug/runtime/js/KittieFetcher.ts
src/test/resources/com/atomist/rug/runtime/js/KittieFetcherWithMappedParams.ts
src/test/resources/com/atomist/rug/runtime/js/interop/KittieFetcherWithSecrets.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerExecuteInstructionCallingRespondable.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerReturningEmptyMessage.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerReturningMessage.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerWithBadStubUse.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerWithNullDefault.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerWithSameParametersConfig.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandWithPresentable.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/command/CommandHandlers.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/517_Pulled.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/EventHandlers.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/EventHandlersAgainstGenerated.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/PlanBuilderTest.scala

**BREAKING at version uptake/compile time**
* EventPlan extends Plan (now abstract) and is returned from Event Handlers
* CommandPlan extends Plan and is returned from Command Handlers
* ResponseHandlers can now return EventPlan | CommandPlan (not ideal, but progress as it enforces a choice).

More specific typings for handler responses

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/plans/LocalPlanRunner.scala
src/main/scala/com/atomist/rug/runtime/plans/PlanResultInterpreter.scala
src/main/scala/com/atomist/rug/runtime/plans/PlanUtils.scala
src/main/scala/com/atomist/rug/spi/Handlers.scala
src/test/resources/com/atomist/rug/kind/java23/ClassAnnotated.ts
src/test/resources/com/atomist/rug/runtime/plans/HandlerThatHandlesAnError.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/PassingFeature1Steps2d.ts
src/test/resources/logback-test.xml
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/plans/ExampleRugFunction.scala
src/test/scala/com/atomist/rug/runtime/plans/LocalPlanRunnerTest.scala

Currently handled errors returned by executed Plan.Instructions are logged and interpreted as failed plans. Now a `Handled` status is set on instructions responses if their failure is handled by a response handler. I'm a little concerned that I may have missed some cases, so I'd appreciate the once over from @claymccoy if possible.
Also, reduce logging/noise from some tests as per #498.

Introduce Handled status for use when instruction errors are handled

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/JavaScriptEventHandler.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsPathExpressionEngine.scala
src/main/typescript/node_modules/@atomist/rug/tree/PathExpression.ts
src/main/typescript/node_modules/@atomist/rug/tree/TransformingPathExpressionEngine.ts
src/test/resources/com/atomist/project/archive/MyHandlers.ts
src/test/resources/com/atomist/rug/runtime/js/EditorInjectedWithPathExpression.ts
src/test/resources/com/atomist/rug/runtime/js/EditorInjectedWithPathExpressionUsingWith.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/517_Pulled.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/EventHandlers.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/EventHandlersAgainstGenerated.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/PushProject.ts
src/test/scala/com/atomist/rug/runtime/js/EditorTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala

The TypeScript `Match` type used functions rather than property access. This was inconsistent with other usage and could produce extremely confusing error messages if property access syntax was used.

Match uses property access

---

CHANGELOG.md
src/main/scala/com/atomist/rug/test/gherkin/AbstractExecutableFeature.scala
src/main/scala/com/atomist/rug/test/gherkin/DefaultExecutableFeatureFactory.scala
src/main/scala/com/atomist/rug/test/gherkin/ExecutableFeatureFactory.scala
src/main/scala/com/atomist/rug/test/gherkin/GherkinRunner.scala
src/main/scala/com/atomist/rug/test/gherkin/ScenarioWorld.scala
src/main/scala/com/atomist/rug/test/gherkin/handler/AbstractHandlerScenarioWorld.scala
src/main/scala/com/atomist/rug/test/gherkin/handler/command/CommandHandlerFeature.scala
src/main/scala/com/atomist/rug/test/gherkin/handler/command/CommandHandlerScenarioWorld.scala
src/main/scala/com/atomist/rug/test/gherkin/handler/event/EventHandlerFeature.scala
src/main/scala/com/atomist/rug/test/gherkin/handler/event/EventHandlerScenarioWorld.scala
src/main/scala/com/atomist/rug/test/gherkin/project/ProjectManipulationFeature.scala
src/main/scala/com/atomist/rug/test/gherkin/project/ProjectScenarioWorld.scala
src/main/typescript/node_modules/@atomist/rug/test/ScenarioWorld.ts
src/main/typescript/node_modules/@atomist/rug/test/handler/Core.ts
src/main/typescript/node_modules/@atomist/rug/test/project/Core.ts
src/main/typescript/node_modules/@atomist/rug/test/project/WellKnownSteps.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/command/LooksInRealProjectsSteps.ts
src/test/resources/com/atomist/rug/test/gherkin/project/RealEditSteps.ts
src/test/resources/com/atomist/rug/test/gherkin/project/real_edit.feature
src/test/resources/com/atomist/rug/test/gherkin/project/real_edit_with_branch.feature
src/test/scala/com/atomist/rug/test/gherkin/handler/command/GherkinRunnerCommandHandlerTest.scala
src/test/scala/com/atomist/rug/test/gherkin/project/GherkinRunnerAgainstProjectTest.scala

Adds the ability to clone repos from GitHub in Gherkin tests. This is convenient for testing against real projects.
Future enhancements may allow for caching, but this provides the core support.
Breaks interface with CLI, as discussed with @cdupuis

Added repo cloning support to handler testing

---

CHANGELOG.md
src/main/scala/com/atomist/project/archive/AtomistConfig.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptProjectOperationTest.scala
src/test/scala/com/atomist/rug/test/gherkin/handler/command/GherkinRunnerCommandHandlerTest.scala
src/test/scala/com/atomist/rug/test/gherkin/project/ProjectTestTargets.scala

On travis-rugs (after npm install), this improved the performance of `rug describe archive -l` from average of 18s to 2.5s (on my machine) over 5 runs.

Improve archive loading performance by selecting specific directories

---

CHANGELOG.md
src/main/scala/com/atomist/rug/kind/core/FileArtifactBackedMutableView.scala
src/main/scala/com/atomist/rug/kind/core/FileMutableView.scala
src/main/scala/com/atomist/rug/spi/CommonViewOperations.scala
src/main/scala/com/atomist/rug/spi/ReflectiveFunctionExport.scala
src/main/scala/com/atomist/rug/spi/TypeOperation.scala
src/main/scala/com/atomist/rug/ts/AbstractTypeScriptGenerator.scala
src/main/scala/com/atomist/rug/ts/TypeScriptInterfaceGenerator.scala
src/main/scala/com/atomist/rug/ts/TypeScriptStubClassGenerator.scala

- Adds ability to generate deprecation warnings in TypeScript generated interfaces for exposed JVM methods marked as `@Deprecated`.
- Deprecates some old methods from `FileMutableView` and other types

Ability to generate deprecation warnings in TypeScript

---

CHANGELOG.md
src/main/scala/com/atomist/rug/test/gherkin/AbstractExecutableFeature.scala
src/test/scala/com/atomist/rug/test/gherkin/GherkinReaderTest.scala
src/test/scala/com/atomist/rug/test/gherkin/project/GherkinRunnerAgainstProjectTest.scala

Include unimplemented TypeScript Given and When steps in the testing
results.  The CLI seems to handle the change fine, reporting them in
the same manner it does unimplemented Then steps.
Closes #570

Report unimplemented Given/When Gherkin steps

---

CHANGELOG.md
src/main/scala/com/atomist/rug/test/gherkin/AbstractExecutableFeature.scala
src/main/typescript/node_modules/@atomist/rug/test/handler/WellKnownSteps.ts
src/main/typescript/node_modules/@atomist/rug/test/project/WellKnownSteps.ts
src/test/scala/com/atomist/rug/test/gherkin/project/GherkinRunnerAgainstProjectTest.scala
src/test/scala/com/atomist/rug/test/gherkin/project/ProjectTestTargets.scala

Add special case of Gherkin `Then` case allowing tests to see if a
scenario was aborted due to an exception being thrown.  Add TypeScript
`Then the scenario was aborted` step implementation so it can be
discovered but it is not actually used.
Add Typescript `Given nothing` step implementation for command handler
testing.
Fix test that was passing due to the wrong failure, adding assertion
to make sure it does not happen again.
Clean up change log.
Closes #569

Allow testing of aborted scenarios

---

CHANGELOG.md
src/main/scala/com/atomist/rug/BadRugException.scala
src/main/scala/com/atomist/rug/runtime/js/BaseJavaScriptHandlerFinder.scala
src/main/typescript/node_modules/@atomist/rug/operations/Decorators.ts
src/test/resources/com/atomist/rug/runtime/js/interop/HandlerWithoutExplicitName.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala

I didn't know this was possible before, and it won't work if we use other ways of constructing things, but should be OK for whenever we use the class decorators.

Use TypeScript classname if name parameter to decorator not passed

---

CHANGELOG.md
src/main/scala/com/atomist/rug/test/gherkin/AbstractExecutableFeature.scala
src/main/typescript/node_modules/@atomist/rug/test/Result.ts
src/main/typescript/node_modules/@atomist/rug/test/ScenarioWorld.ts
src/main/typescript/node_modules/@atomist/rug/test/handler/Core.ts
src/main/typescript/node_modules/@atomist/rug/test/handler/WellKnownSteps.ts
src/main/typescript/node_modules/@atomist/rug/test/project/Core.ts
src/main/typescript/node_modules/@atomist/rug/test/project/Helpers.ts
src/main/typescript/node_modules/@atomist/rug/test/project/WellKnownSteps.ts

Add types to callback signatures of TypeScript implementations of the
Gherkin well-known steps for projects and handlers.  This uncovered a
few errors, including:
-   The Scala implementation of ProjectScenarioWorld.modificationsMade()
returns a boolean, so changed its TypeScript interface to do the
same
-   The Scala implementation of
ProjectMutableView.copyEditorBackingProject() takes no arguments,
so changed its use in the Given step to not pass any
Using specific types for the world parameter was preferred to using
the more generic, e.g., CommandHandlerScenarioWorld was used
preferentially to ScenarioWorld where possible.
Consistent names for the project and world callback arguments.
Closes #574
Add copyright and license information.
Import from specific files rather than mode/Core. …

Add types to Gherkin well-known steps

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/ResponseHandler.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandler.scala
src/main/scala/com/atomist/rug/runtime/plans/LocalInstructionRunner.scala
src/main/typescript/rug/operations/Handlers.ts
src/test/resources/com/atomist/rug/runtime/js/ResponseHandlerAccessingContext.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandlerTest.scala

It's optional in the `HandleResponse` interface, and is exactly the same as that exposed in CommandHandlers...just EventHandlers to go! ;)

Make HandlerContext available to ResponseHandlers #587

---

CHANGELOG.md
src/main/scala/com/atomist/project/generate/ProjectGenerator.scala
src/main/scala/com/atomist/rug/kind/core/ProjectMutableView.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptProjectGenerator.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsGitProjectLoader.scala
src/main/scala/com/atomist/rug/test/gherkin/project/ProjectScenarioWorld.scala
src/main/scala/com/atomist/rug/ts/AbstractTypeScriptGenerator.scala
src/main/typescript/rug/operations/GitProjectLoader.ts
src/main/typescript/rug/operations/ProjectEditor.ts
src/test/scala/com/atomist/rug/runtime/js/EditorTest.scala

Backward compatible. Solves 2 important cases:
- It's now possible to start with an empty repo, regardless of the content of a generator's Rug archive. This is useful when emitting content programmatically, rather than transforming static content.
- It's now possible to start with a git reference. This means we can point a generator at _any_ accessible repo.

Add ability to start a generator with an empty repo or Git repo

---

src/main/scala/com/atomist/rug/kind/xml/XmlMutableView.scala

The 'indent-number' property is only implemented by this impl, so specify it.
Without this, any other TransformerFactory on the classpath will be chosen instead. This causes this function to fail sometimes, depending on what other extensions are loaded.

Be specific about the XML Parser implementation

---

CHANGELOG.md
src/main/scala/com/atomist/project/archive/ArchiveRugResolver.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandler.scala
src/main/scala/com/atomist/rug/runtime/js/PlanBuilder.scala
src/test/resources/com/atomist/rug/runtime/js/ResponseHandlerWithInjectedValues.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandlerTest.scala

This enables us to emit handler chains automatically, allow upstream handlers to pass arbitrary parameters to downstream ones, setting the properties directly on the instance (if no property by that name already exists).
I'm using this for auto-generating handler chains, but given the experience is that response handlers are rarely reused/resuable, this could be used generally too.

Pass parameters to ResponseHandlers blindly if none declared & some passed

---

CHANGELOG.md
src/main/scala/com/atomist/rug/test/gherkin/ScenarioWorld.scala
src/main/scala/com/atomist/rug/test/gherkin/project/ProjectScenarioWorld.scala
src/main/typescript/rug/test/project/Core.ts
src/test/resources/com/atomist/rug/test/gherkin/project/EditorWithoutParametersSteps.ts

Without this, we see plenty tests containing:
```typescript
project.editWith("ChangeLogEditor", { } );
```
which is ugly, especially in JS world.

Allow editWith and generateWith world operations without parameters

---

CHANGELOG.md
src/main/scala/com/atomist/rug/BadRugException.scala
src/main/scala/com/atomist/rug/runtime/ResponseHandler.scala
src/main/scala/com/atomist/rug/runtime/ScopedRug.scala
src/main/scala/com/atomist/rug/runtime/TestDescriptor.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandler.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandler.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptUtils.scala
src/main/typescript/rug/operations/Decorators.ts
src/test/resources/com/atomist/rug/runtime/js/HandlerIntegrationTest.ts
src/test/resources/com/atomist/rug/runtime/js/ResponseHandlerWithArchiveScope.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandlerTest.scala

@IntegrationTest decorator which declares a CommandHandler but has additional details about the test. This will allow us to show them differently in the CLI/Bot should we choose to do so. Adding @Intent will expose via the bot as normal.
Also, add basic scoping support for Rugs. Currently only for Response Handlers:
- "archive" scope means that a Rug should not be visible outside the archive
- "default" scope is what is set by default on all Response Handlers
This is _only_ exposed via `Decorators.ts/setScope` for now as discussions indicated we weren't sure how this would play out. @russmiles certainly thinks that this would be useful for some editors that are just used within archives when composing others.

Changes to support Integration Testing in Rug

---

.atomist/TreePrinter.ts
.atomist/package.json
.gitignore
CHANGELOG.md
src/main/scala/com/atomist/rug/kind/grammar/TypeUnderFile.scala
src/main/scala/com/atomist/tree/content/text/ImmutablePositionedTreeNode.scala
src/main/scala/com/atomist/tree/content/text/OverwritableTextInFile.scala
src/main/scala/com/atomist/tree/content/text/PositionedTreeNode.scala
src/main/scala/com/atomist/tree/content/text/TextTreeNodeLifecycle.scala
src/main/scala/com/atomist/tree/utils/NodeUtils.scala
src/test/resources/com/atomist/rug/kind/PandaParsingTypeScriptTest.ts
src/test/scala/com/atomist/rug/kind/RugIsExtensible.scala
src/test/scala/com/atomist/rug/kind/grammar/AbstractTypeUnderFileTest.scala
src/test/scala/com/atomist/rug/kind/yaml/YamlFileTypeTest.scala
src/test/scala/com/atomist/rug/kind/yaml/YamlFileTypeUsageTest.scala

Please don't squash.
Two improvements for language extensions:
* smaller interface to provide for parsed nodes
* optional preprocess/postprocess steps for cleverness 
this will be useful for the Elm one

Make Language Extensions easier

---

src/main/scala/com/atomist/rug/kind/RugLanguageExtensionTest.scala
src/test/resources/com/atomist/rug/kind/Sample.panda
src/test/scala/com/atomist/rug/kind/RugIsExtensible.scala

This lets me quickly test a path expression against a language extension
It's great for demos. And we can write a language-extension generator that uses it.

Test superclass for extensions

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/plans/LocalPlanRunner.scala
src/main/scala/com/atomist/rug/runtime/plans/PlanResultInterpreter.scala
src/main/scala/com/atomist/rug/runtime/plans/PlanResultLogger.scala
src/main/scala/com/atomist/rug/runtime/plans/PlanRunner.scala
src/main/scala/com/atomist/rug/runtime/plans/PlanUtils.scala
src/main/scala/com/atomist/rug/spi/Handlers.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/PlanBuilderTest.scala
src/test/scala/com/atomist/rug/runtime/plans/LocalPlanRunnerTest.scala
src/test/scala/com/atomist/rug/runtime/plans/PlanResultInterpreterTest.scala
src/test/scala/com/atomist/rug/runtime/plans/PlanResultLoggerTest.scala

This is to remove runtime complications with using Scala's global `ExecutionContext`.
Those changes have been tested in `rug-runner`.

Remove Scala Futures from PlanRunner API

---

CHANGELOG.md
src/main/typescript/rug/operations/Handlers.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala

Since you can create multiple updatable messages with the same ID in
the same Rug, setting timestamp when creating the TypeScript object
can lead to different messages having the same ID.  Leave it undefined
so it gets set by the Rug runtime.
Add aliases for those mapped parameters that did not have them.
Export LocallyRenderedMessage as this is a useful superclass for
response, directed, and updatable messages.
Delint/format TypeScript files touched.
Addresses #654

Not set timestamp when creating UpdatableMessage

---

src/main/scala/com/atomist/util/lang/JavaScriptArray.scala
src/test/scala/com/atomist/util/lang/JavaScriptArrayTest.scala

Slice with out-of-bounds numbers works OK in JS, so we should allow them here instead of failing with exceptions.

Make slice impl more true to JS

---

src/main/scala/com/atomist/tree/marshal/LinkableContainerTreeNode.scala

It was repeating the list of children after each child.
It looked like this, which is confusing:
com.atomist.rug.runtime.js.SourceLanguageRuntimeException: [SafeCommittingProxy#679511233 around LinkableContainerTreeNode: (ChatChannel,-dynamic); isDefault:[name,provider,normalizedName,id,team,isDefault]; team:[name,provider,normalizedName,id,team,isDefault]; normalizedName:[name,provider,normalizedName,id,team,isDefault]; provider:[name,provider,normalizedName,id,team,isDefault]; id:[name,provider,normalizedName,id,team,isDefault]; name:[name,provider,normalizedName,id,team,isDefault] is not an Object] at .atomist/handlers/event/BotJoinedChannel.ts:67/66
console.log("Atomist was invited to " + Object.keys(match.root.channel).join(","));

Remove confusion from toString
