src/main/scala/com/atomist/rug/kind/core/FileArtifactMutableView.scala
src/main/scala/com/atomist/rug/kind/docker/DockerMutableView.scala
src/main/scala/com/atomist/rug/kind/docker/Dockerfile.scala
src/main/scala/com/atomist/rug/kind/docker/DockerfileLine.scala
src/test/scala/com/atomist/rug/kind/core/FileArtifactMutableViewTest.scala
src/test/scala/com/atomist/rug/kind/docker/DockerfileParserTest.scala
src/test/scala/com/atomist/rug/kind/docker/DockerfileTest.scala

Made some changes to support idempotent text changes to files.
Extended the DockerType to access EXPOSE statements which I plan to use for the K8 editor

Kubernetes editor

---

src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectEditor.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectGenerator.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptOperationFinder.scala
src/main/scala/com/atomist/util/lang/TypescriptArray.scala
src/test/scala/com/atomist/rug/runtime/js/TypeScriptRugEditorTest.scala
src/test/scala/com/atomist/util/lang/TypescriptArrayTest.scala

- Create a util.List decorator that implements all the TS array functions (map, filter, reduce etc) so that they can be used from TS like regular arrays
- Decorate ProjectMutableView with something that uses the List decorator so that things file PMV.files() can be used as a regular TS array.

#22 - Implement TS array fns on List

---

src/main/scala/com/atomist/util/scalaparsing/CommonTypesParser.scala
src/test/scala/com/atomist/rug/kind/elm/PredicateTest.scala

let it happen at the top level after all the parsing is done

We don't have to pad every time

---

src/test/resources/elm-start-static-page/.atomist/editors/NewStaticPage.rug
src/test/resources/elm-start-static-page/build
src/test/resources/elm-start-static-page/elm-package.json
src/test/resources/elm-start-static-page/resources/index.html
src/test/resources/elm-start-static-page/resources/styles.css
src/test/resources/elm-start-static-page/src/Main.elm

Looks like this is used. Travis found the failure

---

CHANGELOG.md

https://github.com/atomist/rug/pull/68
@gotcha like this?

Document the 'not' feature in changelog

---

src/main/scala/com/atomist/rug/command/DefaultCommandRegistry.scala
src/main/scala/com/atomist/rug/command/ServiceLoaderCommandRegistry.scala
src/main/scala/com/atomist/rug/kind/core/ProjectType.scala
src/main/scala/com/atomist/rug/runtime/js/interop/PathExpressionExposer.scala
src/main/scala/com/atomist/rug/spi/Command.scala
src/main/scala/com/atomist/rug/spi/CommandRegistry.scala
src/test/scala/com/atomist/rug/runtime/js/interop/SafeCommittingProxyTest.scala

This PR adds a new extension point allowing users add bahavior to any of Rug's `TreeNode` instances.

Initial version of Command loading

---

src/main/scala/com/atomist/rug/test/RugTestParser.scala
src/main/scala/com/atomist/rug/test/RugTestTokens.scala
src/main/scala/com/atomist/rug/test/TestScenario.scala
src/test/scala/com/atomist/rug/test/TestScriptParserRugTest.scala

this will let us test for editor idempotence
Working with @gotcha on this.
So far we have implemented the parsing, but it won't actually run the editor

Issue 70: rug-test: add operations in given

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectEditor.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperation.scala
src/main/scala/com/atomist/rug/runtime/js/interop/ContextMatch.scala
src/main/scala/com/atomist/rug/runtime/js/interop/SafeCommittingProxy.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsPathExpressionEngine.scala
src/main/scala/com/atomist/util/lang/JavaScriptArray.scala
src/main/typescript/node_modules/@atomist/rug/operations/Handler.ts
src/main/typescript/node_modules/@atomist/rug/operations/RugOperation.ts
src/main/typescript/node_modules/@atomist/rug/tree/PathExpression.ts
src/test/scala/com/atomist/rug/kind/elm/ElmTypeUsageTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperationTest.scala
src/test/scala/com/atomist/rug/runtime/js/TypeScriptRugEditorTest.scala
src/test/scala/com/atomist/util/lang/JavaScriptArrayTest.scala

* 'tags' and 'displayable' are now extracted properly from JS #151 and #148
* Rename some TS stuff to JS (it was JS anyway)
* Change usage of 'String' to 'string' and Array to [] in static TS model

Extract Parameters from TS properly

---

src/main/scala/com/atomist/param/ParameterValidationPatterns.scala
src/main/scala/com/atomist/rug/parser/DefaultIdentifierResolver.scala
src/test/scala/com/atomist/param/ParameterValidationPatternsTest.scala
src/test/scala/com/atomist/rug/UsesTest.scala
src/test/scala/com/atomist/rug/parser/CommonRugParserTest.scala

Add a paramter validation regular expression for version ranges.
Sprinkle some parameter validation regex tags in tests.

Add @version_range parameter validation regex

---

src/main/scala/com/atomist/rug/kind/pom/PomMutableView.scala

Addresses atomist/end-user-documentation#43

Minor doc fix

---

CHANGELOG.md
src/main/scala/com/atomist/param/AllowedValue.scala
src/main/scala/com/atomist/param/Parameter.scala
src/main/scala/com/atomist/rug/BadRugException.scala
src/main/scala/com/atomist/rug/parser/CommonRugProductionsParser.scala
src/main/scala/com/atomist/rug/parser/ParserCombinatorRugParser.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperation.scala
src/main/typescript/node_modules/@atomist/rug/operations/RugOperation.ts
src/test/scala/com/atomist/param/ParameterGenerator.scala
src/test/scala/com/atomist/param/ParameterTest.scala
src/test/scala/com/atomist/param/ParametersToTest.scala
src/test/scala/com/atomist/rug/parser/CommonRugParserTest.scala
src/test/scala/com/atomist/rug/parser/RugEditorParserTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperationTest.scala
src/test/scala/com/atomist/rug/runtime/js/TypeScriptRugEditorTest.scala
src/test/scala/com/atomist/rug/runtime/lang/js/NashornConstructorTest.scala

Default parameter values are now being checked against valid values, as
defined by either the parameter's validation regular expression or its
list of valid values.
Addresses #168

Check default parameter values

---

travis-build.bash

If the tests fail, THE BUILD SHOULD PLEASE FAIL

This wins if the build fails

---

src/main/scala/com/atomist/rug/BadRugException.scala
src/main/scala/com/atomist/util/scalaparsing/CommonTypesParser.scala
src/main/scala/com/atomist/util/scalaparsing/ErrorInfo.scala
src/test/scala/com/atomist/rug/parser/RugEditorParserTest.scala

https://github.com/atomist/rug/issues/174 is not a bug. Improved error message for such an ill-formed string.

Better string error handling, addresses #174 (not a bug)

---

CHANGELOG.md
pom.xml
src/test/scala/com/atomist/rug/AbstractRuntimeTest.scala
src/test/scala/com/atomist/rug/kind/core/ProjectMutableViewTest.scala

Update to latest version of artifact-source to fix its bug where deltas
were lost when performing multiple changes.  Add tests to ensure this
stays fixed here too.
Addresses #199

Update artifact-source to fix #199

---

travis-build.bash

But this time be sure to check the exit status of the tests.

Only run tests once on travis

---

src/main/scala/com/atomist/rug/kind/dynamic/ContainerTreeNodeView.scala
src/main/scala/com/atomist/tree/content/text/AbstractMutableContainerTreeNode.scala
src/main/scala/com/atomist/tree/content/text/MutableTerminalTreeNode.scala
src/main/scala/com/atomist/tree/content/text/SimpleMutableContainerTreeNode.scala
src/main/scala/com/atomist/tree/content/text/TreeNodeOperations.scala
src/main/scala/com/atomist/tree/content/text/ViewTree.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/Concat.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/DismatchReport.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/Literal.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/MatcherMicrogrammar.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/Regex.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/Rep.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/dsl/MatcherDefinitionParser.scala
src/main/scala/com/atomist/tree/content/text/microgrammar/primitives.scala
src/main/scala/com/atomist/tree/treeNode.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/DismatchReportTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/MatcherMicrogrammarTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/MatcherOperationsTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/MatcherDefinitionParserTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/MatcherDefinitionUsageTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/MicrogrammarPathExpressionTest.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/TypeScriptMicrogrammarTest.scala

This solves https://github.com/atomist/rug/issues/231 
It adds a concept of significance: "Did the user ask for this node?" vs "Did we add this node to make the tree hang together?"
It makes name optional on Regex.
I think those are the only interesting bits.

231: a test fix that is several fixes

---

CHANGELOG.md
src/main/scala/com/atomist/rug/kind/yml/YmlType.scala
src/test/scala/com/atomist/rug/kind/pom/PomUsageTest.scala
src/test/scala/com/atomist/rug/kind/yml/YmlUsageTest.scala

Implement findAllIn for YmlType so you can actually use it

---

src/main/scala/com/atomist/rug/kind/properties/PropertiesMutableView.scala
src/test/scala/com/atomist/rug/kind/properties/PropertiesMutableViewTest.scala

Added CRLF to new properties when added to a properties file

---

src/main/resources/META-INF/services/com.atomist.rug.spi.Typed
src/main/resources/grammars/antlr/Rug.g4
src/main/scala/com/atomist/rug/kind/rug/dsl/RugType.scala
src/test/resources/com/atomist/rug/kind/rug/ListEditors.ts
src/test/resources/com/atomist/rug/kind/rug/ListEditorsUsingSemanticVersion.ts
src/test/resources/com/atomist/rug/kind/rug/ListParams.ts
src/test/resources/com/atomist/rug/kind/rug/ListUses.ts
src/test/resources/com/atomist/rug/kind/rug/ReplaceEditorWithGenerator.ts
src/test/scala/com/atomist/rug/kind/rug/RugFileTypeTest.scala
src/test/scala/com/atomist/rug/kind/rug/RugFileTypeUsageTest.scala

Hopefully covers all our cases
see #249

Add an ANTLR grammar for Rug DSL

---

src/main/scala/com/atomist/rug/ts/RugTranspiler.scala
src/main/typescript/node_modules/@atomist/rug/operations/ProjectEditor.ts
src/main/typescript/node_modules/@atomist/rug/operations/ProjectGenerator.ts
src/test/scala/com/atomist/rug/runtime/js/TypeScriptRugEditorTest.scala

Remove use of Result and Parameter in some tests

---

CHANGELOG.md
src/main/scala/com/atomist/project/edit/ProjectEditorSupport.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperation.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptInvokingProjectOperationTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptOperationFinderTest.scala

and make sure we set default parameters before validation #224

Require parameters by default in TS

---

src/main/scala/com/atomist/rug/ts/TypeScriptInterfaceGenerator.scala

Changed inheritance from all interfaces extending TreeNode to an inheritance hierarchy

TS interface inheritance

---

src/main/scala/com/atomist/rug/runtime/plans/LocalInstructionRunner.scala
src/main/scala/com/atomist/rug/runtime/plans/ProjectFinder.scala
src/main/scala/com/atomist/rug/runtime/plans/ProjectPersister.scala

Just changes an API which is not out in the wild yet (just used on my dev branches), so CHANGELOG update not relevant.

Add rug & params to finder and persister

---

src/main/scala/com/atomist/rug/BadRugException.scala
src/main/scala/com/atomist/rug/kind/core/ProjectMutableView.scala
src/main/scala/com/atomist/rug/runtime/CommandHandler.scala
src/main/scala/com/atomist/rug/runtime/EventHandler.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandler.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptEventHandler.scala
src/main/scala/com/atomist/rug/runtime/js/RugContext.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsPathExpressionEngine.scala
src/main/scala/com/atomist/rug/runtime/plans/LocalInstructionRunner.scala
src/main/scala/com/atomist/rug/runtime/plans/LocalPlanRunner.scala
src/test/resources/com/atomist/project/archive/MyHandlers.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/plans/LocalPlanRunnerTest.scala

- throw exceptions for bad plans from instruction runner
- log everything to debug instead of info
- **BREAKING** move RugContext out of interop package!

Tweak PlanRunner output

---

src/main/scala/com/atomist/param/MappedParameter.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptUtils.scala
src/main/scala/com/atomist/rug/runtime/plans/MappedParameterSupport.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala

No CHANGELOG entry as this is just fixing an issue before it's been noticed by anybody else :)

Ensure mapped parameters are actually set on the command handler

---

src/main/scala/com/atomist/param/Parameterized.scala
src/main/scala/com/atomist/param/ParameterizedSupport.scala

Should have no impact except for making it easier from other JVM languages.

Move Parameter behaviour to support trait

---

src/main/scala/com/atomist/rug/runtime/js/PlanBuilder.scala
src/main/scala/com/atomist/rug/runtime/plans/LocalPlanRunner.scala
src/main/scala/com/atomist/rug/runtime/plans/PlanUtils.scala
src/main/scala/com/atomist/rug/spi/Handlers.scala
src/main/typescript/node_modules/@atomist/rug/operations/Handlers.ts
src/test/resources/com/atomist/project/archive/MyHandlers.ts

I’m not happy with the naming and looking for feedback.

No callbacks when a plan is returned.

---

src/main/scala/com/atomist/rug/kind/core/ProjectMutableView.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsSafeCommittingProxy.scala
src/main/scala/com/atomist/rug/runtime/rugdsl/DefaultViewFinder.scala
src/main/scala/com/atomist/rug/spi/Typed.scala
src/main/scala/com/atomist/rug/spi/UsageSpecificTypeRegistry.scala
src/main/scala/com/atomist/tree/pathexpression/ExpressionEngine.scala
src/main/scala/com/atomist/tree/pathexpression/LocationStep.scala
src/main/scala/com/atomist/tree/pathexpression/NamedNodeTest.scala
src/main/scala/com/atomist/tree/pathexpression/NodeTest.scala
src/main/scala/com/atomist/tree/pathexpression/NodesWithTag.scala
src/main/scala/com/atomist/tree/pathexpression/PathExpressionEngine.scala
src/main/scala/com/atomist/tree/pathexpression/PredicatedNodeTest.scala
src/main/scala/com/atomist/tree/utils/NodeUtils.scala
src/test/scala/com/atomist/tree/content/text/microgrammar/dsl/MicrogrammarPathExpressionTest.scala
src/test/scala/com/atomist/tree/pathexpression/PathExpressionsAgainstProjectTest.scala
src/test/scala/com/atomist/tree/utils/NodeUtilsTest.scala

Also some other cleanup in path expression engine and `Typed` information handling.

Fixes #360: Introduce property axis

---

pom.xml
src/main/scala/com/atomist/rug/runtime/js/ExceptionEnhancer.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptContext.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptProjectOperation.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptUtils.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsSafeCommittingProxy.scala
src/test/resources/com/atomist/rug/runtime/js/interop/DeliberateNpe.ts
src/test/scala/com/atomist/rug/TestUtils.scala
src/test/scala/com/atomist/rug/runtime/js/interop/RuntimeExceptionHandlingTest.scala

Looks in `JavaScriptContext` for relevant JS and TS sources to improve error reporting. Also suppresses irrelevant Java stack trace and unpacks Nashorn error information.
Introduces a dependency on Atlassian Java Source Map library.
Also some minor tidying in `jsSafeCommittingProxy`.

Improved JavaScript runtime error reporting

---

CHANGELOG.md
src/main/scala/com/atomist/rug/BadRugException.scala
src/main/scala/com/atomist/rug/runtime/CommandHandler.scala
src/main/scala/com/atomist/rug/runtime/InstructionResponse.scala
src/main/scala/com/atomist/rug/runtime/plans/LocalInstructionRunner.scala
src/main/scala/com/atomist/rug/runtime/plans/SecretResolver.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptResponseHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/plans/ExampleRugFunction.scala
src/test/scala/com/atomist/rug/runtime/plans/SecretResolverTest.scala
src/test/scala/com/atomist/rug/runtime/plans/TestSecretResolver.scala

also - InstructionResponse is now a case class.

Support for secret token replacement in Rug Function parameters

---

src/main/scala/com/atomist/rug/test/gherkin/AbstractExecutableFeature.scala
src/main/scala/com/atomist/rug/test/gherkin/ProjectManipulationFeature.scala
src/test/resources/com/atomist/rug/test/gherkin/FindCorruption.ts
src/test/scala/com/atomist/rug/test/gherkin/GherkinReaderTest.scala
src/test/scala/com/atomist/rug/test/gherkin/GherkinRunnerTest.scala

Added BDD test support for Rug reviewers. Fixes #187

---

CHANGELOG.md
src/main/scala/com/atomist/rug/spi/AnnotatedRugFunction.scala
src/main/scala/com/atomist/rug/spi/annotation/Parameter.java
src/main/scala/com/atomist/rug/spi/annotation/RugFunction.java
src/main/scala/com/atomist/rug/spi/annotation/Secret.java
src/main/scala/com/atomist/rug/spi/annotation/Tag.java
src/test/scala/com/atomist/rug/runtime/plans/AnnotatedRugFunctionTest.scala
src/test/scala/com/atomist/rug/runtime/plans/ExampleAnnotatedRugFunction.scala

Code largely taken from another project created by @cdupuis

Add annotations and helper class for implementing RugFunctions

---

src/main/scala/com/atomist/rug/runtime/plans/DefaultRugFunctionRegistry.scala
src/main/scala/com/atomist/rug/runtime/plans/ServiceLoaderRugFunctionRegistry.scala
src/test/scala/com/atomist/rug/runtime/plans/RugFunctionRegistryTest.scala

Minor change to unreleased code -> no CHANGELOG

Support for fully qualified classname lookup for Rug Functions

---

src/main/scala/com/atomist/rug/runtime/js/ExceptionEnhancer.scala
src/main/scala/com/atomist/rug/test/gherkin/AbstractExecutableFeature.scala
src/main/scala/com/atomist/rug/test/gherkin/Result.scala
src/main/scala/com/atomist/rug/test/gherkin/TestReport.scala
src/test/resources/com/atomist/rug/test/gherkin/FailingGenerator.ts
src/test/resources/com/atomist/rug/test/gherkin/SimpleGenerator.ts
src/test/scala/com/atomist/parse/java/ParsingTargets.scala
src/test/scala/com/atomist/rug/test/gherkin/GherkinReaderTest.scala
src/test/scala/com/atomist/rug/test/gherkin/GherkinRunnerTest.scala

Correctly handles exceptions in Gherkin-based tests. Verifies that generators can be tested. More informative test results.

Improved error handling in Gherkin-based tests

---

src/main/scala/com/atomist/rug/test/gherkin/AbstractExecutableFeature.scala
src/main/scala/com/atomist/rug/test/gherkin/GherkinRunner.scala
src/main/scala/com/atomist/rug/test/gherkin/ProjectManipulationFeature.scala
src/main/scala/com/atomist/rug/test/gherkin/TestReport.scala
src/main/typescript/node_modules/@atomist/rug/test/Core.ts
src/test/resources/com/atomist/rug/test/gherkin/AlpEditor.ts
src/test/resources/com/atomist/rug/test/gherkin/SimpleGeneratorWithParams.ts
src/test/scala/com/atomist/rug/test/gherkin/GherkinReaderTest.scala
src/test/scala/com/atomist/rug/test/gherkin/GherkinRunnerTest.scala

There are still some odds things happening when somewhere inside Rug an exception is being thrown. Not really clear to me if that should stop the test execution completely.

Support for calling nested editors from generators

---

src/main/resources/META-INF/services/com.atomist.rug.spi.Typed
src/main/scala/com/atomist/rug/kind/core/ArtifactContainerMutableView.scala
src/main/scala/com/atomist/rug/kind/core/DirectoryMutableView.scala
src/main/scala/com/atomist/rug/kind/core/ProjectMutableView.scala
src/main/scala/com/atomist/tree/pathexpression/PathExpressionEngine.scala
src/test/resources/com/atomist/rug/kind/core/AccessDirectory.ts
src/test/resources/com/atomist/rug/kind/core/Replacer.ts
src/test/resources/com/atomist/rug/kind/core/ReplacerClj.ts
src/test/scala/com/atomist/rug/kind/core/DirectoryMutableViewTest.scala
src/test/scala/com/atomist/rug/kind/core/DirectoryMutableViewUsageTest.scala
src/test/scala/com/atomist/rug/kind/core/ProjectMutableViewTest.scala

Also some minor tidying of TypeScript test files.

Fixes #406: Directory extension now exposed

---

src/main/scala/com/atomist/rug/kind/xml/XmlType.scala
src/test/scala/com/atomist/rug/kind/xml/XmlTypeTest.scala

XmlType from FileMutableView

---

CHANGELOG.md
src/main/scala/com/atomist/rug/test/gherkin/AbstractExecutableFeature.scala
src/main/scala/com/atomist/rug/test/gherkin/Definitions.scala
src/main/typescript/node_modules/@atomist/rug/test/handler/Core.ts
src/main/typescript/node_modules/@atomist/rug/test/project/Core.ts
src/test/resources/com/atomist/rug/test/gherkin/project/ParameterizedFeatureSteps.ts
src/test/scala/com/atomist/rug/test/gherkin/project/GherkinRunnerAgainstProjectTest.scala
src/test/scala/com/atomist/rug/test/gherkin/project/ProjectTestTargets.scala

Fixes #431: Support for parameterized Gherkin steps

---

CHANGELOG.md
src/main/scala/com/atomist/rug/test/gherkin/handler/AbstractHandlerScenarioWorld.scala
src/main/typescript/node_modules/@atomist/rug/test/handler/Core.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/EventHandlers.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/PassingFeature2Steps.ts
src/test/scala/com/atomist/rug/test/gherkin/handler/event/EventHandlerTestTargets.scala
src/test/scala/com/atomist/rug/test/gherkin/handler/event/GherkinRunnerEventHandlerTest.scala

Not sure this covers everything we need.

Allow to call .message() on world during test #457

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandler.scala
src/main/scala/com/atomist/rug/runtime/js/JavaScriptUtils.scala
src/main/scala/com/atomist/rug/runtime/js/PlanBuilder.scala
src/main/scala/com/atomist/rug/runtime/plans/LocalInstructionRunner.scala
src/main/scala/com/atomist/rug/runtime/plans/LocalPlanRunner.scala
src/test/scala/com/atomist/rug/runtime/js/PlanBuilderTest.scala

Also remove some empty scala files

Don't pass through null/undefined instruction parameters #466

---

pom.xml
src/main/scala/com/atomist/rug/test/gherkin/ScenarioWorld.scala
src/main/scala/com/atomist/rug/ts/AbstractTypeScriptGenerator.scala
src/main/scala/com/atomist/rug/ts/CortexTypeGenerator.scala
src/main/scala/com/atomist/rug/ts/CortexTypeGeneratorApp.scala
src/main/scala/com/atomist/rug/ts/TypeScriptStubClassGenerator.scala
src/test/scala/com/atomist/rug/rugdoc/TypeScriptStubClassGeneratorTest.scala
src/test/scala/com/atomist/rug/ts/CortexTypeGeneratorTest.scala
src/test/scala/com/atomist/rug/ts/TypeScriptBuilder.scala

- Improved generated stub classes. Cleaner formatting, better ordering of fields and functions, and improved Typedoc.
- Renamed generation classes (Scala) to convey their purpose.
- Minor refactoring to make it easier to eventually source JSON metadata from a URL rather than a String loaded from the class path

Polishing of generated TypeScript

---

src/main/typescript/node_modules/@atomist/rug/gulpfile.js

Build TypeDoc for everything

---

src/main/scala/com/atomist/rug/kind/pom/PomMutableView.scala
src/test/resources/springboot1/pomWithPluginManagement.xml
src/test/scala/com/atomist/rug/kind/pom/PomMutableViewTest.scala
src/test/scala/com/atomist/rug/kind/xml/XmlTypeTest.scala

* isBuildPluginManagementPresent
* addOrReplaceBuildPluginManagementPlugin
See gh-430

Add new methods for pluginManagement

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/interop/jsScalaHidingProxy.scala
src/main/scala/com/atomist/rug/test/gherkin/handler/AbstractHandlerScenarioWorld.scala
src/main/scala/com/atomist/rug/test/gherkin/handler/command/CommandHandlerScenarioWorld.scala
src/main/scala/com/atomist/rug/test/gherkin/handler/event/EventHandlerScenarioWorld.scala
src/main/scala/com/atomist/util/lang/JavaScriptArray.scala
src/main/typescript/node_modules/@atomist/rug/test/handler/Core.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/EventHandlers.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/PassingFeature1Steps5.ts
src/test/scala/com/atomist/rug/test/gherkin/handler/event/GherkinRunnerEventHandlerTest.scala

Fixes #480. Can now record multiple plans

---

src/main/scala/com/atomist/rug/kind/pom/PomMutableView.scala
src/test/resources/springboot1/pomWithProfile.xml
src/test/scala/com/atomist/rug/kind/pom/PomMutableViewTest.scala
src/test/scala/com/atomist/rug/kind/xml/XmlTypeTest.scala

New operation is added to POM Rug type which add a new profile with it's
content.

Add addOrReplaceProfile Pom

---

src/main/typescript/node_modules/@atomist/rug/operations/Handlers.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala

Also change minor typo `MessageMimetypes` to `MessageMimeTypes`.

Move to addAddress for all addressable messages

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/interop/AbstractJSProxy.scala
src/main/scala/com/atomist/rug/runtime/js/interop/JsonableProxy.scala
src/main/scala/com/atomist/rug/runtime/js/interop/NashornMapBackedGraphNode.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsScalaHidingProxy.scala
src/main/scala/com/atomist/tree/content/text/OverwritableTextTreeNode.scala
src/main/typescript/node_modules/@atomist/rug/ast/DecoratingPathExpressionEngine.ts
src/main/typescript/node_modules/@atomist/rug/ast/java/Structures.ts
src/main/typescript/node_modules/@atomist/rug/tree/TreeHelper.ts
src/test/resources/com/atomist/rug/kind/java/path/CompareMethods.ts
src/test/scala/com/atomist/rug/runtime/js/interop/NashornBackedGraphNodeTest.scala
src/test/scala/com/atomist/rug/runtime/js/interop/jsSafeCommittingProxyTest.scala

Significantly stringification in both Java and TypeScript.
Also some more experimentation with `JavaFileType` related AST manipulation TypeScript.

Fixes #521. Improved stringification of nodes

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/BaseJavaScriptHandlerFinder.scala
src/test/resources/com/atomist/rug/runtime/js/ReopenIssueHandler.ts
src/test/resources/com/atomist/rug/runtime/js/ReopenIssueHandlerInArray.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala

Now finds handlers in JavaScript arrays as well as scalar `vars`. This will be useful when users use functions to create handlers.

Supports handler arrays

---

src/main/scala/com/atomist/rug/kind/core/ProjectMutableView.scala
src/main/scala/com/atomist/rug/spi/ParameterOrReturnType.scala
src/main/scala/com/atomist/rug/spi/ReflectiveFunctionExport.scala
src/main/scala/com/atomist/rug/spi/TypeRegistry.scala
src/main/scala/com/atomist/rug/ts/CortexTypeGenerator.scala
src/main/scala/com/atomist/util/lang/TypeScriptGenerationHelper.scala

Cleans up some generation code: More consistent and removes duplication

Improved type conversion in TypeScript generation

---

pom.xml

Reporting section in POM is under project, not profiles.  Centralize
maven-scala-plugin version.
Fixes #556

Move reporting section to right place

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/PlanBuilder.scala
src/main/scala/com/atomist/rug/spi/Handlers.scala
src/main/typescript/node_modules/@atomist/rug/operations/Handlers.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerReturningDirectedMessageWithInstructions.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala
src/test/scala/com/atomist/rug/runtime/plans/LocalPlanRunnerTest.scala

Also add optional id to Presentable instruction
Related to #562

Add instructions to DirectedMessage and ResponseMessage

---

CHANGELOG.md
src/main/typescript/node_modules/@atomist/rug/ast/AstHelper.ts
src/main/typescript/node_modules/@atomist/rug/ast/DecoratingPathExpressionEngine.ts
src/main/typescript/node_modules/@atomist/rug/ast/TextTreeNodeOps.ts
src/main/typescript/node_modules/@atomist/rug/ast/TreeDiff.ts
src/main/typescript/node_modules/@atomist/rug/ast/java/Expressions.ts
src/main/typescript/node_modules/@atomist/rug/ast/java/Model.ts
src/main/typescript/node_modules/@atomist/rug/ast/java/Structures.ts
src/main/typescript/node_modules/@atomist/rug/ast/scala/ScalaPathExpressionEngine.ts
src/main/typescript/node_modules/@atomist/rug/ast/scala/Types.ts
src/main/typescript/node_modules/@atomist/rug/ast/yaml/Types.ts
src/main/typescript/node_modules/@atomist/rug/ast/yaml/YamlPathExpressionEngine.ts
src/main/typescript/node_modules/@atomist/rug/operations/Decorators.ts
src/main/typescript/node_modules/@atomist/rug/operations/HandlerUtils.ts
src/main/typescript/node_modules/@atomist/rug/operations/Handlers.ts
src/main/typescript/node_modules/@atomist/rug/operations/ProjectEditor.ts
src/main/typescript/node_modules/@atomist/rug/operations/ProjectGenerator.ts
src/main/typescript/node_modules/@atomist/rug/operations/RugOperation.ts
src/main/typescript/node_modules/@atomist/rug/test/Result.ts
src/main/typescript/node_modules/@atomist/rug/test/ScenarioWorld.ts
src/main/typescript/node_modules/@atomist/rug/test/handler/Core.ts
src/main/typescript/node_modules/@atomist/rug/test/handler/WellKnownSteps.ts
src/main/typescript/node_modules/@atomist/rug/test/project/Core.ts
src/main/typescript/node_modules/@atomist/rug/test/project/Helpers.ts
src/main/typescript/node_modules/@atomist/rug/test/project/WellKnownSteps.ts
src/main/typescript/node_modules/@atomist/rug/tslint.json
src/test/resources/com/atomist/rug/kind/java/path/CompareMethods.ts

Fix issue #566

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/JavaScriptEventHandler.scala
src/main/scala/com/atomist/rug/runtime/js/RugContext.scala
src/main/scala/com/atomist/rug/runtime/js/interop/jsContextMatch.scala
src/main/typescript/rug/tree/PathExpression.ts
src/main/typescript/rug/tree/TransformingPathExpressionEngine.ts
src/test/resources/com/atomist/rug/test/gherkin/handler/event/EventHandlersAgainstGenerated.ts

Context root is now available in all handlers, as is path expression engine

Added context root to event handlers via Match

---

src/main/scala/com/atomist/rug/runtime/js/PlanBuilder.scala
src/main/scala/com/atomist/rug/spi/Handlers.scala
src/main/typescript/rug/operations/Handlers.ts
src/test/resources/com/atomist/rug/runtime/js/EditInstructionWithTarget.ts
src/test/scala/com/atomist/rug/runtime/js/PlanBuilderTest.scala

Previous CHANGELOG entry covers this
Also includes some minor typo fixes, and some naming changes to be more consistent with the GitHub API.

Ability for edits to happen on branch without a PR #581

---

CHANGELOG.md
src/main/typescript/rug/operations/Handlers.ts
src/test/resources/com/atomist/rug/runtime/js/EventHandlerWithLifecycleMessage.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerReturningDirectedMessageWithInstructions.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptEventHandlerTest.scala

Add Identifiable instruction and remove unused id from Presentable instruction

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/plans/LocalInstructionRunner.scala

Paired with @jessitron on this one.

Return failure when generate fails

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/JavaScriptRugFinder.scala
src/main/typescript/rug/operations/Decorators.ts
src/test/resources/com/atomist/rug/runtime/js/EmitHandler.ts
src/test/resources/com/atomist/rug/runtime/js/SimpleHandlerWithHiddenProperties.ts
src/test/scala/com/atomist/rug/runtime/js/EditorTest.scala
src/test/scala/com/atomist/rug/runtime/js/JavaScriptDecoratorTest.scala

So that we can emit rugs programmatically.

Expose underlying decorator logic #595 & hide defined properties #554

---

src/main/scala/com/atomist/rug/runtime/js/JavaScriptUtils.scala

In the last release of Rug, it was ok for parameters to default to "" even if they have a minLength of 1 (and required: true).
That isn't true in master now. Which makes atomist:rug-rugs not compile. Very not-backward-compatible.
This makes it true again. It prints a warning:
```
Loading rugs of atomist:rug-rugs (0.31.0-20170524133032·zip) completed
WARNING: On rug AddLicense, parameter 'include' has a default value of '', but that is not a valid value for this parameter. Set the parameter to null instead, please.
```
FYI, the error when I try to load atomist:rug-rugs on master before this change is:
```
Initializing shell for atomist:rug-rugs (0.31.0-20170524133032·zip) failed
Parameter include default value () is not valid: Parameter{name='include', description='if provided, editor will …
```

Restore leniency on default values that aren't valid

---

CHANGELOG.md
src/main/scala/com/atomist/rug/runtime/js/PlanBuilder.scala
src/main/scala/com/atomist/rug/spi/Handlers.scala
src/main/typescript/rug/operations/Handlers.ts
src/test/resources/com/atomist/rug/runtime/js/interop/SimpleCommandHandlerReturningUpdatableMessageWithMessageIdAndTimestamp.ts
src/test/scala/com/atomist/rug/runtime/js/JavaScriptCommandHandlerTest.scala

@tanya-coding could you take a look at this please?

Add post property to UpdatableMessage
